project_id = "fbjlgepxbyoyradaacvd"

[functions.onboard-organization]
verify_jwt = false

[functions.create-user]
enabled = true
verify_jwt = true
entrypoint = "./functions/create-user/index.ts"

[functions.delete-user]
enabled = true
verify_jwt = false
entrypoint = "./functions/delete-user/index.ts"

[functions.bulk-create-users]
enabled = true
verify_jwt = true
entrypoint = "./functions/bulk-create-users/index.ts"

[functions.setup-admin]
enabled = true
verify_jwt = true
entrypoint = "./functions/setup-admin/index.ts"

[functions.sync-teambuildr]
enabled = true
verify_jwt = true
entrypoint = "./functions/sync-teambuildr/index.ts"
