-- Global Injury Master Data Seed
-- 1. Delete existing data (as requested)
DELETE FROM public.injury_master_data;

INSERT INTO public.injury_master_data (organization_id, region, injury_type, diagnosis)
VALUES
    (NULL, 'Head', 'Muscle injury', 'Facial muscle trigger points'),
    (NULL, 'Head', 'Muscle injury', 'Muscular trigger point referred headache'),
    (NULL, 'Head', 'Nerve injury', 'Concussion with imaging abnormality'),
    (NULL, 'Head', 'Nerve injury', 'Concussion with abnormal biomarkers'),
    (NULL, 'Head', 'Nerve injury', 'Acute Concussion with visual symptoms'),
    (NULL, 'Head', 'Nerve injury', 'Concussion in a player with a concerning history'),
    (NULL, 'Head', 'Nerve injury', 'Concussion with Criteria 1 video signs'),
    (NULL, 'Head', 'Nerve injury', 'Concussion'),
    (NULL, 'Head', 'Nerve injury', 'Intracranial Bleed'),
    (NULL, 'Head', 'Nerve injury', 'Cranial Nerve injury'),
    (NULL, 'Head', 'Nerve injury', 'Chronic Brain Injury'),
    (NULL, 'Head', 'Nerve injury', 'Concussion with no concerning history or signs'),
    (NULL, 'Head', 'Nerve injury', 'Concussion/Brain Injury'),
    (NULL, 'Head', 'Nerve injury', 'Traumatic Encephalopathy Syndrome'),
    (NULL, 'Head', 'Nerve injury', 'Concussion with delayed symptom presentation'),
    (NULL, 'Head', 'Nerve injury', 'Concussion with Criteria 2 video signs'),
    (NULL, 'Head', 'Fracture', 'Compound fractured mandible'),
    (NULL, 'Head', 'Fracture', 'Other orbital fracture not otherwise specified'),
    (NULL, 'Head', 'Fracture', 'Maxillary fracture'),
    (NULL, 'Head', 'Fracture', 'Fractured frontal bone'),
    (NULL, 'Head', 'Fracture', 'Mandible fracture'),
    (NULL, 'Head', 'Fracture', 'Fractured Tooth'),
    (NULL, 'Head', 'Fracture', 'Medial Wall orbit fracture'),
    (NULL, 'Head', 'Fracture', 'Skull/cranial fracture'),
    (NULL, 'Head', 'Fracture', 'Avulsed/fractured tooth'),
    (NULL, 'Head', 'Fracture', 'Orbital floor fracture'),
    (NULL, 'Head', 'Fracture', 'Head/Facial fracture'),
    (NULL, 'Head', 'Fracture', 'Nose fracture'),
    (NULL, 'Head', 'Fracture', 'Zygoma fracture'),
    (NULL, 'Head', 'Fracture', 'Orbital fracture'),
    (NULL, 'Head', 'Ligament', 'Jaw sprain/temporomandibular joint (TMJ) symptoms'),
    (NULL, 'Head', 'Ligament', 'Jaw bruising/haematoma'),
    (NULL, 'Head', 'Ligament', 'Facial Joint sprain/injury'),
    (NULL, 'Head', 'Joint sprain', 'Facial Dislocation'),
    (NULL, 'Head', 'Joint sprain', 'Avulsed Tooth'),
    (NULL, 'Head', 'Joint sprain', 'Jaw dislocation'),
    (NULL, 'Head', 'Contusion/vascular', 'Ear bruising/haematoma'),
    (NULL, 'Head', 'Contusion/vascular', 'Head/facial contusion/haematoma'),
    (NULL, 'Head', 'Contusion/vascular', 'Nose contusion/haematoma'),
    (NULL, 'Head', 'Contusion/vascular', 'Septal haematoma'),
    (NULL, 'Head', 'Contusion/vascular', 'Periorbital bruising/haematoma'),
    (NULL, 'Head', 'Contusion/vascular', 'Mouth bruising/haematoma'),
    (NULL, 'Head', 'Contusion/vascular', 'Scalp bruising/haematoma'),
    (NULL, 'Head', 'Contusion/vascular', 'Eye bruising/haematoma'),
    (NULL, 'Head', 'Contusion/vascular', 'Cauliflower Ear (chronic)'),
    (NULL, 'Head', 'Contusion/vascular', 'Epistaxis'),
    (NULL, 'Head', 'Contusion/vascular', 'Other bruising/haematoma not otherwise specified'),
    (NULL, 'Head', 'Laceration', 'Eyelid laceration requiring suturing'),
    (NULL, 'Head', 'Laceration', 'Lip laceration'),
    (NULL, 'Head', 'Laceration', 'Tongue laceration requiring suturing'),
    (NULL, 'Head', 'Laceration', 'Nose laceration requiring suturing'),
    (NULL, 'Head', 'Laceration', 'Nose laceration not requiring suturing'),
    (NULL, 'Head', 'Laceration', 'Perforating mouth laceration requiring suturing'),
    (NULL, 'Head', 'Laceration', 'Chin laceration'),
    (NULL, 'Head', 'Laceration', 'Tongue laceration'),
    (NULL, 'Head', 'Laceration', 'Mucosal laceration requiring suturing'),
    (NULL, 'Head', 'Laceration', 'Tongue laceration not requiring suturing'),
    (NULL, 'Head', 'Laceration', 'Head laceration location unspecified/or multiple not requiring suturing'),
    (NULL, 'Head', 'Laceration', 'Head laceration location unspecified/or multiple requiring suturing'),
    (NULL, 'Head', 'Laceration', 'Facial laceration requiring suturing'),
    (NULL, 'Head', 'Laceration', 'Perforating mouth laceration'),
    (NULL, 'Head', 'Laceration', 'Ear laceration'),
    (NULL, 'Head', 'Laceration', 'Ear laceration requiring suturing'),
    (NULL, 'Head', 'Laceration', 'Mucosal laceration not requiring suturing'),
    (NULL, 'Head', 'Laceration', 'Forehead laceration requiring suturing'),
    (NULL, 'Head', 'Laceration', 'Eyebrow laceration requiring suturing'),
    (NULL, 'Head', 'Laceration', 'Lip laceration requiring suturing'),
    (NULL, 'Head', 'Laceration', 'Forehead laceration not requiring suturing'),
    (NULL, 'Head', 'Laceration', 'Eyelid laceration'),
    (NULL, 'Head', 'Laceration', 'Facial laceration not requiring suturing'),
    (NULL, 'Head', 'Laceration', 'Head/facial laceration'),
    (NULL, 'Head', 'Laceration', 'Eyelid laceration not requiring suturing'),
    (NULL, 'Head', 'Laceration', 'Eyebrow laceration not requiring suturing'),
    (NULL, 'Head', 'Laceration', 'Cheek laceration not requiring suturing'),
    (NULL, 'Head', 'Laceration', 'Scalp laceration'),
    (NULL, 'Head', 'Laceration', 'Complication of head laceration including infection'),
    (NULL, 'Head', 'Laceration', 'Cheek laceration requiring suturing'),
    (NULL, 'Head', 'Abrasion', 'Scalp abrasion'),
    (NULL, 'Head', 'Abrasion', 'Chin abrasion'),
    (NULL, 'Head', 'Abrasion', 'Cheek abrasion'),
    (NULL, 'Head', 'Abrasion', 'Nose abrasion'),
    (NULL, 'Head', 'Abrasion', 'Lip abrasion not requiring suturing'),
    (NULL, 'Head', 'Abrasion', 'Forehead abrasion'),
    (NULL, 'Head', 'Abrasion', 'Facial abrasion not otherwise specified'),
    (NULL, 'Head', 'Abrasion', 'Ear abrasion'),
    (NULL, 'Head', 'Abrasion', 'Mouth abrasion'),
    (NULL, 'Head', 'Abrasion', 'Eyebrow abrasion'),
    (NULL, 'Head', 'Organ trauma', 'Corneal Abrasion'),
    (NULL, 'Head', 'Organ trauma', 'Ear trauma'),
    (NULL, 'Head', 'Organ trauma', 'Traumatic retinal haemorrhage'),
    (NULL, 'Head', 'Organ trauma', 'Perforated ear drum'),
    (NULL, 'Head', 'Organ trauma', 'Subluxed Tooth'),
    (NULL, 'Head', 'Organ trauma', 'Eye injury/trauma'),
    (NULL, 'Head', 'Organ trauma', 'Head Organ Damage'),
    (NULL, 'Head', 'Organ trauma', 'Hyphema'),
    (NULL, 'Head', 'Organ trauma', 'Retinal detachment'),
    (NULL, 'Head', 'Organ trauma', 'Eye foreign body - not otherwise specified'),
    (NULL, 'Head', 'Organ trauma', 'Eye foreign body - Corneal'),
    (NULL, 'Head', 'Organ trauma', 'Contact lens displacement'),
    (NULL, 'Head', 'Organ trauma', 'Conjunctival haematoma'),
    (NULL, 'Head', 'Pain without tissue type specified', 'Functional head pain'),
    (NULL, 'Head', 'Pain without tissue type specified', 'Facial muscle strain'),
    (NULL, 'Head', 'Unknown', 'Headache/pain undiagnosed'),
    (NULL, 'Head', 'Unknown', 'Head impact (not concussion) with Criteria 2 video signs'),
    (NULL, 'Head', 'Unknown', 'Head/neck impact not diagnosed as concussion'),
    (NULL, 'Head', 'Unknown', 'Head Injuries'),
    (NULL, 'Neck', 'Muscle injury', 'Neck muscle strain'),
    (NULL, 'Neck', 'Muscle injury', 'Neck muscle soreness/spasm/torticollis'),
    (NULL, 'Neck', 'Muscle contusion', 'Neck contusion/haematoma'),
    (NULL, 'Neck', 'Nerve injury', 'Neurological Neck Injury'),
    (NULL, 'Neck', 'Nerve injury', 'Cervical spinal cord concussion'),
    (NULL, 'Neck', 'Nerve injury', 'Cervical spinal canal stenosis'),
    (NULL, 'Neck', 'Nerve injury', 'Cervical nerve root compression/stretch'),
    (NULL, 'Neck', 'Nerve injury', 'Cervical spinal cord injury'),
    (NULL, 'Neck', 'Fracture', 'Neck Fracture'),
    (NULL, 'Neck', 'Fracture', 'Unstable cervical fracture/s'),
    (NULL, 'Neck', 'Fracture', 'Avulsion fracture/s cervical spine (e.g. spinous process fracture)'),
    (NULL, 'Neck', 'Fracture', 'Cervical Fracture/s'),
    (NULL, 'Neck', 'Fracture', 'Stable cervical fracture/s'),
    (NULL, 'Neck', 'Bone stress injury', 'Cervical stress fracture'),
    (NULL, 'Neck', 'Cartilage', 'Cervical Disc sprain'),
    (NULL, 'Neck', 'Cartilage', 'Cervical disc Injury'),
    (NULL, 'Neck', 'Cartilage', 'Cervical Disc Prolapse'),
    (NULL, 'Neck', 'Cartilage', 'Cervical disc degeneration'),
    (NULL, 'Neck', 'Arthritis', 'Cervical spinal column degenerative disc disease/arthritis'),
    (NULL, 'Neck', 'Arthritis', 'Cervical facet joint arthritis'),
    (NULL, 'Neck', 'Ligament', 'Facet Joint/Neck Ligament sprain'),
    (NULL, 'Neck', 'Ligament', 'Whiplash/neck sprain'),
    (NULL, 'Neck', 'Chronic instability', 'Cervical Spine Instability'),
    (NULL, 'Neck', 'Chronic instability', 'Cervical Subluxation/instability'),
    (NULL, 'Neck', 'Laceration', 'Complication of neck laceration including infection'),
    (NULL, 'Neck', 'Laceration', 'Neck laceration requiring suturing'),
    (NULL, 'Neck', 'Laceration', 'Neck Laceration'),
    (NULL, 'Neck', 'Laceration', 'Neck laceration not requiring suturing'),
    (NULL, 'Neck', 'Abrasion', 'Neck abrasion'),
    (NULL, 'Neck', 'Organ trauma', 'Neck Organ Damage'),
    (NULL, 'Neck', 'Organ trauma', 'Laryngeal trauma'),
    (NULL, 'Neck', 'Organ trauma', 'Laryngeal fracture'),
    (NULL, 'Neck', 'Organ trauma', 'Foreign body in larynx'),
    (NULL, 'Neck', 'Pain without tissue type specified', 'Cervical functional pain'),
    (NULL, 'Neck', 'Pain without tissue type specified', 'Cervicogenic headache'),
    (NULL, 'Neck', 'Pain without tissue type specified', 'Neck muscle and/or tendon strain/spasm/trigger points'),
    (NULL, 'Neck', 'Unknown', 'Neck Pain/Injury Not Otherwise Specified'),
    (NULL, 'Neck', 'Unknown', 'Neck pain undiagnosed'),
    (NULL, 'Neck', 'Unknown', 'Post neck surgery'),
    (NULL, 'Neck', 'Unknown', 'Structural Abnormality Cervical Spine'),
    (NULL, 'Neck', 'Unknown', 'Neck Injuries'),
    (NULL, 'Shoulder', 'Muscle injury', 'Shoulder muscle trigger points/posterior muscle soreness'),
    (NULL, 'Shoulder', 'Muscle injury', 'Muscle strain, shoulder region'),
    (NULL, 'Shoulder', 'Muscle injury', 'Deltoid muscle injury'),
    (NULL, 'Shoulder', 'Muscle injury', 'Rotator Cuff muscle injury'),
    (NULL, 'Shoulder', 'Muscle injury', 'Latissimus dorsi muscle strain'),
    (NULL, 'Shoulder', 'Muscle injury', 'Other shoulder muscle injury not elsewhere specified'),
    (NULL, 'Shoulder', 'Muscle injury', 'Pectoralis major muscle strain'),
    (NULL, 'Shoulder', 'Muscle contusion', 'Shoulder muscle haematoma'),
    (NULL, 'Shoulder', 'Muscle contusion', 'Deltoid haematoma'),
    (NULL, 'Shoulder', 'Muscle contusion', 'A/C Joint contusion'),
    (NULL, 'Shoulder', 'Muscle contusion', 'Shoulder region contusion'),
    (NULL, 'Shoulder', 'Muscle contusion', 'Shoulder contusion/haematoma'),
    (NULL, 'Shoulder', 'Tendinopathy', 'Biceps tendinopathy'),
    (NULL, 'Shoulder', 'Tendinopathy', 'Shoulder impingement/Synovitis'),
    (NULL, 'Shoulder', 'Tendinopathy', 'Calcific tendinopathy'),
    (NULL, 'Shoulder', 'Tendinopathy', 'Shoulder tendon injury not otherwise specified'),
    (NULL, 'Shoulder', 'Tendinopathy', 'Other Infraspinatus tendon injury Not otherwise specified'),
    (NULL, 'Shoulder', 'Tendinopathy', 'Acute anterior internal impingement'),
    (NULL, 'Shoulder', 'Tendinopathy', 'Subscapularis Tendon Injury'),
    (NULL, 'Shoulder', 'Tendinopathy', 'Other pec major tendon injury not otherwise specified'),
    (NULL, 'Shoulder', 'Tendinopathy', 'Proximal biceps tendon injury'),
    (NULL, 'Shoulder', 'Tendinopathy', 'Infraspinatus tendon injury'),
    (NULL, 'Shoulder', 'Tendinopathy', 'Supraspinatus tendon tear partial thickness'),
    (NULL, 'Shoulder', 'Tendinopathy', 'Multiple tendon injury'),
    (NULL, 'Shoulder', 'Tendinopathy', 'Other Subscapularis tendon injury not otherwise specified'),
    (NULL, 'Shoulder', 'Tendinopathy', 'Supraspinatus tendinopathy'),
    (NULL, 'Shoulder', 'Tendinopathy', 'Other biceps tendon injury not otherwise specified'),
    (NULL, 'Shoulder', 'Tendinopathy', 'Subacromial impingement'),
    (NULL, 'Shoulder', 'Tendinopathy', 'Rotator cuff tendon pathology'),
    (NULL, 'Shoulder', 'Tendon rupture', 'Rupture of long head of biceps tendon'),
    (NULL, 'Shoulder', 'Tendon rupture', 'Pec Major tendon rupture'),
    (NULL, 'Shoulder', 'Tendon rupture', 'Infraspinatus tendon rupture'),
    (NULL, 'Shoulder', 'Tendon rupture', 'Supraspinatus tendon rupture full thickness'),
    (NULL, 'Shoulder', 'Tendon rupture', 'Subscapularis tendon rupture'),
    (NULL, 'Shoulder', 'Nerve injury', 'Brachial plexus traction injury/burner/stinger'),
    (NULL, 'Shoulder', 'Nerve injury', 'Shoulder Neurological injury'),
    (NULL, 'Shoulder', 'Nerve injury', 'Thoracic Outlet Syndrome (neural)'),
    (NULL, 'Shoulder', 'Nerve injury', 'Isolated axillary nerve palsy'),
    (NULL, 'Shoulder', 'Nerve injury', 'Suprascapular nerve entrapment or palsy'),
    (NULL, 'Shoulder', 'Fracture', 'Fracture neck of humerus'),
    (NULL, 'Shoulder', 'Fracture', 'Fractured glenoid /bony Bankart lesion'),
    (NULL, 'Shoulder', 'Fracture', 'Clavicular fracture'),
    (NULL, 'Shoulder', 'Fracture', 'Fracture greater tuberosity humerus'),
    (NULL, 'Shoulder', 'Fracture', 'Fracture inner third clavicle'),
    (NULL, 'Shoulder', 'Fracture', 'Fracture dislocation A/C joint'),
    (NULL, 'Shoulder', 'Fracture', 'Fracture outer third clavicle'),
    (NULL, 'Shoulder', 'Fracture', 'Hill Sachs compression fracture'),
    (NULL, 'Shoulder', 'Fracture', 'Shoulder Fractures'),
    (NULL, 'Shoulder', 'Fracture', 'Fracture middle third clavicle'),
    (NULL, 'Shoulder', 'Fracture', 'Scapula fracture'),
    (NULL, 'Shoulder', 'Fracture', 'Refracture clavicle through callus'),
    (NULL, 'Shoulder', 'Bone stress injury', 'Stress fracture coracoid process'),
    (NULL, 'Shoulder', 'Bone stress injury', 'Other bony/overuse injuries not elsewhere classified'),
    (NULL, 'Shoulder', 'Bone stress injury', 'A/C joint stress/overuse injury'),
    (NULL, 'Shoulder', 'Bone stress injury', 'Shoulder stress/Overuse injuries incl stress fractures'),
    (NULL, 'Shoulder', 'Bone stress injury', 'Shoulder bony stress/over use injury'),
    (NULL, 'Shoulder', 'Physis injury', 'Osteochondrosis shoulder'),
    (NULL, 'Shoulder', 'Physis injury', 'Traction injury to apophysis at shoulder'),
    (NULL, 'Shoulder', 'Cartilage', 'Shoulder dislocation with humeral avulsion of the glenohumeral ligament (HAGL)'),
    (NULL, 'Shoulder', 'Cartilage', 'Superior Labrum Anterior and Posterior (SLAP) lesion shoulder'),
    (NULL, 'Shoulder', 'Cartilage', 'Glenohumeral joint sprain with chondral/labral damage (incl SLAP tear)'),
    (NULL, 'Shoulder', 'Cartilage', 'Shoulder dislocation with labral Bankart lesion'),
    (NULL, 'Shoulder', 'Cartilage', 'Shoulder chondral lesion'),
    (NULL, 'Shoulder', 'Cartilage', 'Posterior shoulder dislocation with posterior labral lesion'),
    (NULL, 'Shoulder', 'Arthritis', 'A/C joint arthritis'),
    (NULL, 'Shoulder', 'Arthritis', 'Osteolysis of distal clavicle'),
    (NULL, 'Shoulder', 'Arthritis', 'A/C joint chronic pain'),
    (NULL, 'Shoulder', 'Arthritis', 'Glenohumeral osteoarthritis (O/A)'),
    (NULL, 'Shoulder', 'Arthritis', 'Shoulder Osteoarthritis'),
    (NULL, 'Shoulder', 'Synovitis / capsulitis', 'Adhesive capsulitis/frozen shoulder'),
    (NULL, 'Shoulder', 'Synovitis / capsulitis', 'Internal impingement of the shoulder'),
    (NULL, 'Shoulder', 'Synovitis / capsulitis', 'Cervical rib'),
    (NULL, 'Shoulder', 'Synovitis / capsulitis', 'Chronic internal impingement'),
    (NULL, 'Shoulder', 'Synovitis / capsulitis', 'Acute posterior internal impingement'),
    (NULL, 'Shoulder', 'Bursitis', 'Other chronic subacromial impingement'),
    (NULL, 'Shoulder', 'Bursitis', 'Instability associated subacromial impingement'),
    (NULL, 'Shoulder', 'Bursitis', 'Acute subacromial impingement'),
    (NULL, 'Shoulder', 'Ligament', 'Grade 3 A/C joint dislocation'),
    (NULL, 'Shoulder', 'Ligament', 'Grade 1 A/C joint sprain'),
    (NULL, 'Shoulder', 'Ligament', 'Acromioclavicular (A/C) joint sprain'),
    (NULL, 'Shoulder', 'Ligament', 'Glenohumeral joint sprains'),
    (NULL, 'Shoulder', 'Ligament', 'Grade 2 A/C joint sprain'),
    (NULL, 'Shoulder', 'Ligament', 'Glenohumeral ligament sprain'),
    (NULL, 'Shoulder', 'Joint sprain', 'Posterior shoulder dislocation'),
    (NULL, 'Shoulder', 'Joint sprain', 'Grade 4-6 A/C joint dislocation'),
    (NULL, 'Shoulder', 'Joint sprain', 'Shoulder dislocation with axillary nerve injury'),
    (NULL, 'Shoulder', 'Joint sprain', 'Shoulder dislocation (anterior)'),
    (NULL, 'Shoulder', 'Joint sprain', 'Acute shoulder subluxation'),
    (NULL, 'Shoulder', 'Joint sprain', 'Shoulder dislocation with other or unspecified neurological injury'),
    (NULL, 'Shoulder', 'Joint sprain', 'Dislocated shoulder'),
    (NULL, 'Shoulder', 'Joint sprain', 'Inferior shoulder dislocation'),
    (NULL, 'Shoulder', 'Joint sprain', 'Glenohumeral ligament tear'),
    (NULL, 'Shoulder', 'Chronic instability', 'Chronic Shoulder instability'),
    (NULL, 'Shoulder', 'Chronic instability', 'Anterior shoulder instability'),
    (NULL, 'Shoulder', 'Chronic instability', 'A/C Joint instability/recurrent sprains'),
    (NULL, 'Shoulder', 'Chronic instability', 'Posterior shoulder instability'),
    (NULL, 'Shoulder', 'Contusion/vascular', 'Subclavian vein obstruction'),
    (NULL, 'Shoulder', 'Contusion/vascular', 'Shoulder vascular thoracic outlet injury'),
    (NULL, 'Shoulder', 'Laceration', 'Shoulder laceration requiring suturing'),
    (NULL, 'Shoulder', 'Laceration', 'Complication of shoulder laceration including infection'),
    (NULL, 'Shoulder', 'Laceration', 'Shoulder laceration not requiring suturing'),
    (NULL, 'Shoulder', 'Abrasion', 'Shoulder Soft Tissue Abrasion'),
    (NULL, 'Shoulder', 'Pain without tissue type specified', 'Shoulder pain without tissue type specified'),
    (NULL, 'Shoulder', 'Unknown', 'Shoulder Pain/Injury not otherwise specified'),
    (NULL, 'Shoulder', 'Unknown', 'Post shoulder reconstruction'),
    (NULL, 'Shoulder', 'Unknown', 'Shoulder pain undiagnosed'),
    (NULL, 'Shoulder', 'Unknown', 'Post A/C joint surgery'),
    (NULL, 'Shoulder', 'Unknown', 'Post shoulder surgery'),
    (NULL, 'Upper Arm', 'Muscle injury', 'Upper arm muscle trigger points/pain'),
    (NULL, 'Upper Arm', 'Muscle injury', 'Biceps muscle strain'),
    (NULL, 'Upper Arm', 'Muscle injury', 'Upper Arm Muscle Strain/Spasm/Trigger points'),
    (NULL, 'Upper Arm', 'Muscle injury', 'Triceps muscle strain'),
    (NULL, 'Upper Arm', 'Muscle injury', 'Upper arm delayed onset muscle soreness (DOMS)'),
    (NULL, 'Upper Arm', 'Muscle contusion', 'Biceps haematoma'),
    (NULL, 'Upper Arm', 'Muscle contusion', 'Upper arm muscle bruising/haematoma'),
    (NULL, 'Upper Arm', 'Muscle contusion', 'Upper Arm Soft Tissue Bruising/Haematoma'),
    (NULL, 'Upper Arm', 'Muscle contusion', 'Upper arm myositis ossificans'),
    (NULL, 'Elbow', 'Joint sprain', 'Dislocated radial head'),
    (NULL, 'Upper Arm', 'Muscle contusion', 'Other Upper arm soft tissue bruising/haematoma'),
    (NULL, 'Upper Arm', 'Muscle contusion', 'Triceps Haematoma'),
    (NULL, 'Upper Arm', 'Tendinopathy', 'Upper Arm Tendon Injury'),
    (NULL, 'Upper Arm', 'Tendon rupture', 'Pectoralis major tendon injury'),
    (NULL, 'Upper Arm', 'Nerve injury', 'Median nerve injury upper arm'),
    (NULL, 'Upper Arm', 'Nerve injury', 'Radial nerve injury upper arm'),
    (NULL, 'Upper Arm', 'Nerve injury', 'Ulnar nerve injury upper arm'),
    (NULL, 'Upper Arm', 'Nerve injury', 'Upper Arm neurological injury'),
    (NULL, 'Upper Arm', 'Nerve injury', 'Musculocutaneous nerve injury upper arm'),
    (NULL, 'Upper Arm', 'Fracture', 'Midshaft humerus fracture'),
    (NULL, 'Upper Arm', 'Fracture', 'Upper Arm Fracture'),
    (NULL, 'Upper Arm', 'Fracture', 'Humerus fracture'),
    (NULL, 'Upper Arm', 'Bone stress injury', 'Stress fracture humerus'),
    (NULL, 'Upper Arm', 'Bone stress injury', 'Upper arm stress fracture'),
    (NULL, 'Upper Arm', 'Bone stress injury', 'Upper Arm Bony Stress /Overuse Injury'),
    (NULL, 'Upper Arm', 'Bone contusion', 'Humerus bone contusion'),
    (NULL, 'Upper Arm', 'Physis injury', 'Little leaguers'' shoulder'),
    (NULL, 'Upper Arm', 'Laceration', 'Upper arm laceration'),
    (NULL, 'Upper Arm', 'Abrasion', 'Upper Arm Abrasion'),
    (NULL, 'Upper Arm', 'Stump injury', 'Infection of stump upper arm'),
    (NULL, 'Upper Arm', 'Stump injury', 'Stump trauma upper arm'),
    (NULL, 'Upper Arm', 'Pain without tissue type specified', 'Other Upper Arm Overuse Injury'),
    (NULL, 'Upper Arm', 'Pain without tissue type specified', 'Upper arm soft tissue overuse injury (e.g. periostitis)'),
    (NULL, 'Upper Arm', 'Unknown', 'Upper Arm Pain/Injury not otherwise specified'),
    (NULL, 'Elbow', 'Muscle injury', 'Elbow muscle strain/spasm/trigger points'),
    (NULL, 'Elbow', 'Tendinopathy', 'Distal triceps tendon injury'),
    (NULL, 'Elbow', 'Tendinopathy', 'Golfer''s elbow (medial epicondyle pain)'),
    (NULL, 'Elbow', 'Tendinopathy', 'Distal triceps tendinopathy'),
    (NULL, 'Elbow', 'Tendinopathy', 'Tennis elbow (lateral epicondyle pain)'),
    (NULL, 'Elbow', 'Tendinopathy', 'Elbow Tendon Injury Combined'),
    (NULL, 'Elbow', 'Tendinopathy', 'Distal biceps tendinopathy'),
    (NULL, 'Elbow', 'Tendinopathy', 'Common extensor origin tear'),
    (NULL, 'Elbow', 'Tendinopathy', 'Common flexor origin tear'),
    (NULL, 'Elbow', 'Tendon rupture', 'Distal triceps tendon rupture'),
    (NULL, 'Elbow', 'Tendon rupture', 'Distal biceps tendon rupture'),
    (NULL, 'Elbow', 'Nerve injury', 'Other nerve entrapment, elbow'),
    (NULL, 'Elbow', 'Nerve injury', 'Ulnar neuropathy, elbow'),
    (NULL, 'Elbow', 'Fracture', 'Avulsion fracture distal humerus'),
    (NULL, 'Elbow', 'Fracture', 'Supracondylar humeral fracture'),
    (NULL, 'Elbow', 'Fracture', 'Avulsion fracture proximal radius'),
    (NULL, 'Elbow', 'Fracture', 'Elbow Fractures'),
    (NULL, 'Elbow', 'Fracture', 'Fractured humeral condyle(s)'),
    (NULL, 'Elbow', 'Fracture', 'Fractured olecranon'),
    (NULL, 'Elbow', 'Fracture', 'Avulsion fracture elbow multiple locations or location unspecified'),
    (NULL, 'Elbow', 'Fracture', 'Fractured radial head'),
    (NULL, 'Elbow', 'Bone stress injury', 'Elbow stress fracture'),
    (NULL, 'Elbow', 'Bone contusion', 'Elbow bone bruise'),
    (NULL, 'Elbow', 'Avascular necrosis', 'Panner disease (elbow avascular necrosis)'),
    (NULL, 'Elbow', 'Physis injury', 'Apophysitis medial epicondyle elbow'),
    (NULL, 'Elbow', 'Physis injury', 'Capitellar osteochondrosis'),
    (NULL, 'Elbow', 'Physis injury', 'Traction injury to apophysis at elbow'),
    (NULL, 'Elbow', 'Cartilage', 'Chondral lesion elbow (+/- loose bodies)'),
    (NULL, 'Elbow', 'Cartilage', 'Loose Body in Elbow'),
    (NULL, 'Elbow', 'Cartilage', 'Osteochondrosis elbow'),
    (NULL, 'Elbow', 'Arthritis', 'Elbow osteoarthritis'),
    (NULL, 'Elbow', 'Synovitis / capsulitis', 'Elbow atraumatic synovitis'),
    (NULL, 'Elbow', 'Synovitis / capsulitis', 'Elbow posterior impingement/synovitis'),
    (NULL, 'Elbow', 'Bursitis', 'Elbow olecranon bursitis'),
    (NULL, 'Elbow', 'Ligament', 'Elbow hyperextension +/- strain anterior elbow structures'),
    (NULL, 'Elbow', 'Ligament', 'Other elbow strain not otherwise specified'),
    (NULL, 'Elbow', 'Ligament', 'Elbow UCL rupture/grade 3 tear'),
    (NULL, 'Elbow', 'Ligament', 'Sprained/jarred elbow'),
    (NULL, 'Elbow', 'Ligament', 'Elbow ulna/medial collateral ligament (UCL) strain or tear'),
    (NULL, 'Elbow', 'Ligament', 'Elbow UCL injury and common flexor origin tear'),
    (NULL, 'Elbow', 'Joint sprain', 'Anterior elbow dislocation'),
    (NULL, 'Elbow', 'Joint sprain', 'Posterior elbow dislocation'),
    (NULL, 'Elbow', 'Joint sprain', 'Dislocated elbow'),
    (NULL, 'Elbow', 'Chronic instability', 'Elbow Instability'),
    (NULL, 'Elbow', 'Chronic instability', 'Elbow posterolateral instability'),
    (NULL, 'Elbow', 'Chronic instability', 'Elbow valgus instability'),
    (NULL, 'Elbow', 'Contusion/vascular', 'Elbow contusion/haematoma'),
    (NULL, 'Elbow', 'Laceration', 'Elbow laceration deep'),
    (NULL, 'Elbow', 'Laceration', 'Elbow laceration'),
    (NULL, 'Elbow', 'Abrasion', 'Elbow abrasion superficial'),
    (NULL, 'Elbow', 'Abrasion', 'Complication of elbow laceration including infection'),
    (NULL, 'Elbow', 'Stump injury', 'Stump trauma elbow'),
    (NULL, 'Elbow', 'Stump injury', 'Infection of stump elbow'),
    (NULL, 'Elbow', 'Pain without tissue type specified', 'Elbow pain without tissue type specified'),
    (NULL, 'Elbow', 'Unknown', 'Elbow pain undiagnosed'),
    (NULL, 'Elbow', 'Unknown', 'Elbow Pain/Injury not otherwise specified'),
    (NULL, 'Elbow', 'Unknown', 'Elbow Injuries'),
    (NULL, 'Elbow', 'Unknown', 'Post elbow surgery'),
    (NULL, 'Forearm', 'Muscle injury', 'Forearm flexor muscle strain'),
    (NULL, 'Forearm', 'Muscle injury', 'Forearm Muscle Injury'),
    (NULL, 'Forearm', 'Muscle injury', 'Forearm muscle soreness'),
    (NULL, 'Forearm', 'Muscle injury', 'Forearm extensor muscle strain'),
    (NULL, 'Forearm', 'Muscle contusion', 'Forearm contusion/haematoma'),
    (NULL, 'Forearm', 'Muscle compartment syndrome', 'Forearm compartment syndrome'),
    (NULL, 'Forearm', 'Tendinopathy', 'Forearm extensor tendinopathy'),
    (NULL, 'Forearm', 'Tendinopathy', 'Forearm splints/medial ulnar stress syndrome'),
    (NULL, 'Forearm', 'Tendinopathy', 'Intersection syndrome'),
    (NULL, 'Forearm', 'Tendinopathy', 'Forearm flexor tendon injury'),
    (NULL, 'Forearm', 'Tendinopathy', 'Forearm extensor tendon injury'),
    (NULL, 'Forearm', 'Tendinopathy', 'Forearm Tendon Injury'),
    (NULL, 'Forearm', 'Tendinopathy', 'Forearm extensor tenosynovitis'),
    (NULL, 'Forearm', 'Nerve injury', 'Forearm Neurological Injury'),
    (NULL, 'Forearm', 'Fracture', 'Fractured ulna midshaft'),
    (NULL, 'Forearm', 'Fracture', 'Galeazzi fracture - midshaft radius fracture, dislocation distal radioulnar joint'),
    (NULL, 'Forearm', 'Fracture', 'Fracture radius and ulna midshaft'),
    (NULL, 'Forearm', 'Fracture', 'Smiths fracture distal radius'),
    (NULL, 'Forearm', 'Fracture', 'Monteggia Fracture - midshaft ulna fracture and dislocation radial head at elbow'),
    (NULL, 'Forearm', 'Fracture', 'Fracture of distal ulna'),
    (NULL, 'Forearm', 'Fracture', 'Fractured forearm bone(s)'),
    (NULL, 'Forearm', 'Fracture', 'Fractured distal radius'),
    (NULL, 'Forearm', 'Fracture', 'Fracture radius midshaft'),
    (NULL, 'Forearm', 'Fracture', 'Colles fracture radius'),
    (NULL, 'Forearm', 'Bone stress injury', 'Stress fracture radius and/or ulna'),
    (NULL, 'Forearm', 'Bone stress injury', 'Forearm Stress Fracture'),
    (NULL, 'Forearm', 'Bone contusion', 'Forearm bone contusion'),
    (NULL, 'Forearm', 'Laceration', 'Complication of forearm laceration including infection'),
    (NULL, 'Forearm', 'Abrasion', 'Forearm Abrasion'),
    (NULL, 'Forearm', 'Stump injury', 'Stump trauma forearm'),
    (NULL, 'Forearm', 'Stump injury', 'Infection of stump forearm'),
    (NULL, 'Forearm', 'Pain without tissue type specified', 'Other Stress/Overuse injuries to Forearm'),
    (NULL, 'Forearm', 'Unknown', 'Forearm Pain/Injury undiagnosed'),
    (NULL, 'Forearm', 'Unknown', 'Forearm Pain/Injury not otherwise specified'),
    (NULL, 'Wrist', 'Muscle injury', 'Wrist and Hand Muscle Injury'),
    (NULL, 'Wrist', 'Muscle contusion', 'Wrist bruising/haematoma'),
    (NULL, 'Wrist', 'Tendinopathy', 'Thumb tendon injury'),
    (NULL, 'Wrist', 'Tendinopathy', 'De Quervain''s tenosynovitis'),
    (NULL, 'Wrist', 'Tendinopathy', 'Wrist ganglion'),
    (NULL, 'Wrist', 'Tendinopathy', 'Rupture wrist flexor tendon'),
    (NULL, 'Wrist', 'Tendinopathy', 'Carpal boss'),
    (NULL, 'Wrist', 'Tendinopathy', 'Wrist Tendon Injury'),
    (NULL, 'Wrist', 'Tendinopathy', 'Wrist extensor tendon injury'),
    (NULL, 'Wrist', 'Tendinopathy', 'wrist extensor tenosynovitis/tendinopathy at wrist'),
    (NULL, 'Wrist', 'Tendinopathy', 'Wrist flexor tenosynovitis/tendinopathy'),
    (NULL, 'Wrist', 'Tendon rupture', 'Rupture thumb extensor tendon (excl if complication of wrist fracture - see specific fracture)'),
    (NULL, 'Wrist', 'Tendon rupture', 'Other tenosynovitis/tendinopathy thumb'),
    (NULL, 'Wrist', 'Tendon rupture', 'Rupture wrist extensor tendon'),
    (NULL, 'Wrist', 'Nerve injury', 'Wrist ulnar nerve injury'),
    (NULL, 'Wrist', 'Nerve injury', 'Carpal Tunnel Syndrome'),
    (NULL, 'Wrist', 'Nerve injury', 'Wrist Neurological Injury'),
    (NULL, 'Wrist', 'Fracture', 'Fractured hamate'),
    (NULL, 'Wrist', 'Fracture', 'Fracture radial styloid'),
    (NULL, 'Wrist', 'Fracture', 'Fracture of ulna styloid'),
    (NULL, 'Wrist', 'Fracture', 'Fractured scaphoid'),
    (NULL, 'Wrist', 'Fracture', 'Fracture other carpal bone'),
    (NULL, 'Wrist', 'Fracture', 'Fracture distal pole scaphoid'),
    (NULL, 'Wrist', 'Fracture', 'Fracture multiple carpal bones'),
    (NULL, 'Wrist', 'Fracture', 'Fractured hook of hamate'),
    (NULL, 'Wrist', 'Fracture', 'Fracture proximal pole scaphoid'),
    (NULL, 'Wrist', 'Fracture', 'Fracture of distal radius +/- ulna'),
    (NULL, 'Wrist', 'Fracture', 'Wrist fracture with complication (e.g. extensor pollicus longus rupture)'),
    (NULL, 'Wrist', 'Fracture', 'Fracture waist scaphoid'),
    (NULL, 'Wrist', 'Fracture', 'Fractured trapezium'),
    (NULL, 'Wrist', 'Bone stress injury', 'Carpal stress fracture'),
    (NULL, 'Wrist', 'Bone stress injury', 'Wrist and Hand Stress/Overuse Injuries'),
    (NULL, 'Wrist', 'Bone stress injury', 'Hand stress fracture (incl thumb and fingers)'),
    (NULL, 'Wrist', 'Bone contusion', 'Other complication of wrist sprain'),
    (NULL, 'Wrist', 'Bone contusion', 'Other carpal ligament injury'),
    (NULL, 'Wrist', 'Bone contusion', 'Distal radioulnar joint injury'),
    (NULL, 'Wrist', 'Avascular necrosis', 'Non union fractured scaphoid'),
    (NULL, 'Wrist', 'Avascular necrosis', 'Avascular necrosis scaphoid'),
    (NULL, 'Wrist', 'Avascular necrosis', 'Avascular necrosis in wrist/hand'),
    (NULL, 'Wrist', 'Avascular necrosis', 'Avascular necrosis lunate'),
    (NULL, 'Wrist', 'Physis injury', 'Epiphysitis of distal radius'),
    (NULL, 'Wrist', 'Physis injury', 'Traction injury to apophysis at wrist/hand'),
    (NULL, 'Wrist', 'Physis injury', 'Osteochondrosis of wrist and hand'),
    (NULL, 'Wrist', 'Cartilage', 'Wrist Osteochondral/Chondral Injury'),
    (NULL, 'Wrist', 'Cartilage', 'Wrist fibrocartilage tear'),
    (NULL, 'Wrist', 'Arthritis', 'Scapholunate advanced collapse (SLAC)'),
    (NULL, 'Wrist', 'Arthritis', 'Wrist (radiocarpal) osteoarthritis'),
    (NULL, 'Wrist', 'Arthritis', 'Wrist Osteoarthritis (O/A)'),
    (NULL, 'Wrist', 'Synovitis / capsulitis', 'Ulnar abutment syndrome'),
    (NULL, 'Wrist', 'Synovitis / capsulitis', 'Chronic synovitis of wrist'),
    (NULL, 'Wrist', 'Ligament', 'Scapholunate ligament sprain'),
    (NULL, 'Wrist', 'Ligament', 'Scapholunate ligament rupture'),
    (NULL, 'Wrist', 'Ligament', 'Scapholunate ligament sprain/tear'),
    (NULL, 'Wrist', 'Ligament', 'Sprained/jarred wrist joint'),
    (NULL, 'Wrist', 'Ligament', 'Lunate - triquetral sprain'),
    (NULL, 'Wrist', 'Joint sprain', 'Wrist and Hand Dislocations'),
    (NULL, 'Wrist', 'Joint sprain', 'Dislocation of CMC joint of fingers'),
    (NULL, 'Wrist', 'Joint sprain', 'Dislocation through carpus'),
    (NULL, 'Wrist', 'Joint sprain', 'Distal radioulnar joint dislocation'),
    (NULL, 'Wrist', 'Joint sprain', 'Dislocation of thumb joint'),
    (NULL, 'Wrist', 'Joint sprain', 'Radiocarpal joint dislocation'),
    (NULL, 'Wrist', 'Chronic instability', 'Carpal instability'),
    (NULL, 'Wrist', 'Chronic instability', 'Thumb Instability'),
    (NULL, 'Wrist', 'Chronic instability', 'Chronic Wrist Instability'),
    (NULL, 'Wrist', 'Chronic instability', 'VISI (Volar intercalated segmental instability) wrist'),
    (NULL, 'Wrist', 'Chronic instability', 'Radiocarpal joint instability'),
    (NULL, 'Wrist', 'Chronic instability', 'Distal radioulnar joint instability'),
    (NULL, 'Wrist', 'Chronic instability', 'Scapholunate Dorsal intercalated segment instability (DISI)'),
    (NULL, 'Wrist', 'Contusion/vascular', 'Finger bruising/haematoma'),
    (NULL, 'Wrist', 'Contusion/vascular', 'Wrist arterial injury (incl aneurysm)'),
    (NULL, 'Wrist', 'Contusion/vascular', 'Wrist Soft Tissue Bruising/Haematoma'),
    (NULL, 'Wrist', 'Contusion/vascular', 'Wrist Vascular Injury'),
    (NULL, 'Wrist', 'Laceration', 'Callous of Wrist/hand (incl fingers/thumb)'),
    (NULL, 'Wrist', 'Laceration', 'Blisters of wrist/hand (incl fingers/thumb)'),
    (NULL, 'Wrist', 'Laceration', 'Palmar hand laceration'),
    (NULL, 'Wrist', 'Laceration', 'Laceration of thumb nail/nailbed'),
    (NULL, 'Wrist', 'Laceration', 'Volar wrist laceration/abrasion'),
    (NULL, 'Wrist', 'Laceration', 'Wrist laceration/abrasion'),
    (NULL, 'Wrist', 'Laceration', 'Dorsal wrist laceration/abrasion'),
    (NULL, 'Wrist', 'Abrasion', 'Wrist abrasion'),
    (NULL, 'Wrist', 'Pain without tissue type specified', 'Wrist and Hand Impingement/Synovitis'),
    (NULL, 'Wrist', 'Unknown', 'Other wrist pain not otherwise specified'),
    (NULL, 'Wrist', 'Unknown', 'Other hand pain not otherwise specified'),
    (NULL, 'Wrist', 'Unknown', 'Post surgery on wrist joint'),
    (NULL, 'Wrist', 'Unknown', 'Other Wrist Injury not otherwise specified'),
    (NULL, 'Wrist', 'Unknown', 'Wrist or hand pain undiagnosed'),
    (NULL, 'Hand', 'Muscle contusion', 'Hand muscle bruising/haematoma'),
    (NULL, 'Hand', 'Tendinopathy', 'Dupytren''s Contracture'),
    (NULL, 'Hand', 'Tendinopathy', 'Trigger thumb'),
    (NULL, 'Hand', 'Tendinopathy', 'Trigger Finger'),
    (NULL, 'Hand', 'Tendinopathy', 'Finger flexor tenosynovitis/tendinopathy'),
    (NULL, 'Hand', 'Tendinopathy', 'Index finger flexor tendon rupture'),
    (NULL, 'Hand', 'Tendinopathy', 'Flexor pully Injury fingers'),
    (NULL, 'Hand', 'Tendon rupture', 'Little finger extensor tendon rupture'),
    (NULL, 'Hand', 'Tendon rupture', 'Index finger extensor tendon rupture'),
    (NULL, 'Hand', 'Tendon rupture', 'Middle finger extensor tendon rupture'),
    (NULL, 'Hand', 'Tendon rupture', 'Rupture thumb flexor tendon'),
    (NULL, 'Hand', 'Tendon rupture', 'Ring finger extensor tendon rupture'),
    (NULL, 'Hand', 'Tendon rupture', 'Little finger flexor tendon rupture'),
    (NULL, 'Hand', 'Tendon rupture', 'Ring finger flexor tendon rupture'),
    (NULL, 'Hand', 'Tendon rupture', 'Middle finger flexor tendon rupture'),
    (NULL, 'Hand', 'Tendon rupture', 'Finger extensor tendon injury (incl mallet finger +/- avulsion fracture distal phalanx)'),
    (NULL, 'Hand', 'Tendon rupture', 'Finger(s) extensor tenosynovitis/tendinopathy'),
    (NULL, 'Hand', 'Tendon rupture', 'Flexor tendon rupture finger(s)'),
    (NULL, 'Hand', 'Fracture', 'Fractured thumb'),
    (NULL, 'Hand', 'Fracture', 'Rolando fracture (comminuted fracture base 1st MC)'),
    (NULL, 'Hand', 'Fracture', 'Multiple phalangeal fractures fingers'),
    (NULL, 'Hand', 'Fracture', 'Multiple metacarpal fractures'),
    (NULL, 'Hand', 'Fracture', 'Bennett''s fracture/dislocation thumb'),
    (NULL, 'Hand', 'Fracture', 'Proximal phalanx fracture index finger'),
    (NULL, 'Hand', 'Fracture', 'Middle phalanx fracture little finger'),
    (NULL, 'Hand', 'Fracture', 'Distal phalanx fracture index finger'),
    (NULL, 'Hand', 'Fracture', 'Middle phalanx fracture middle finger'),
    (NULL, 'Hand', 'Fracture', 'Distal phalanx fracture middle finger'),
    (NULL, 'Hand', 'Fracture', 'Proximal phalanx fracture ring finger'),
    (NULL, 'Hand', 'Fracture', 'Fracture 4th metacarpal'),
    (NULL, 'Hand', 'Fracture', 'Distal phalanx fracture little finger'),
    (NULL, 'Hand', 'Fracture', 'Fracture shaft 1st metacarpal'),
    (NULL, 'Hand', 'Fracture', 'Avulsion fracture phalanx'),
    (NULL, 'Hand', 'Fracture', 'Fractured phalanx'),
    (NULL, 'Hand', 'Fracture', 'Fracture 3rd metacarpal'),
    (NULL, 'Hand', 'Fracture', 'Middle phalanx fracture ring finger'),
    (NULL, 'Hand', 'Fracture', 'Fifth metacarpal fracture'),
    (NULL, 'Hand', 'Fracture', 'Fracture proximal phalanx of thumb'),
    (NULL, 'Hand', 'Fracture', 'Distal phalanx fracture ring finger'),
    (NULL, 'Hand', 'Fracture', 'Proximal phalanx fracture middle finger'),
    (NULL, 'Hand', 'Fracture', 'Proximal phalanx fracture little finger'),
    (NULL, 'Hand', 'Fracture', 'Fracture distal phalanx thumb'),
    (NULL, 'Hand', 'Fracture', 'Middle phalanx fracture index finger'),
    (NULL, 'Hand', 'Fracture', 'Fracture metacarpals 2- 5'),
    (NULL, 'Hand', 'Fracture', 'Fracture 2nd metacarpal'),
    (NULL, 'Hand', 'Bone stress injury', 'Sesamoiditis of thumb'),
    (NULL, 'Hand', 'Bone contusion', 'Hand bone contusion'),
    (NULL, 'Hand', 'Arthritis', 'Metacarpophalangeal (MCP) joint O/A'),
    (NULL, 'Hand', 'Arthritis', 'Carpometacarpal (CMC) joint O/A'),
    (NULL, 'Hand', 'Arthritis', 'Osteoarthritis of fingers'),
    (NULL, 'Hand', 'Arthritis', 'PIP joint O/A fingers'),
    (NULL, 'Hand', 'Arthritis', 'Interphalangeal joint O/A'),
    (NULL, 'Hand', 'Arthritis', 'Osteoarthritis of thumb'),
    (NULL, 'Hand', 'Arthritis', 'DIP joint O/A fingers'),
    (NULL, 'Hand', 'Synovitis / capsulitis', 'Chronic synovitis of thumb'),
    (NULL, 'Hand', 'Synovitis / capsulitis', 'Chronic synovitis of 1st CMC joint'),
    (NULL, 'Hand', 'Synovitis / capsulitis', 'Chronic synovitis of DIP joint(s)'),
    (NULL, 'Hand', 'Synovitis / capsulitis', 'Chronic synovitis of fingers'),
    (NULL, 'Hand', 'Synovitis / capsulitis', 'Chronic Synovitis of IP joint thumb'),
    (NULL, 'Hand', 'Synovitis / capsulitis', 'Chronic synovitis of MCP joint(s)'),
    (NULL, 'Hand', 'Synovitis / capsulitis', 'Chronic synovitis of 1st MCP joint'),
    (NULL, 'Hand', 'Synovitis / capsulitis', 'Chronic synovitis of PIP joint(s)'),
    (NULL, 'Chest', 'Bone stress injury', 'Stress reaction rib(s)'),
    (NULL, 'Hand', 'Synovitis / capsulitis', 'Complication from finger fracture (incl malunion)'),
    (NULL, 'Hand', 'Ligament', 'Thumb radial collateral ligament (RCL) rupture at MCP joint'),
    (NULL, 'Hand', 'Ligament', 'Thumb ulnar collateral ligament (UCL) rupture at MCP joint (skier''s thumb)'),
    (NULL, 'Hand', 'Ligament', 'Sprained ulnar collateral ligament (Skier''s) thumb'),
    (NULL, 'Hand', 'Ligament', 'Other hand or finger ligament tear'),
    (NULL, 'Hand', 'Ligament', 'Metacarpophalangeal joint sprain'),
    (NULL, 'Hand', 'Ligament', 'Thumb sprain'),
    (NULL, 'Hand', 'Ligament', 'Thumb IP joint sprain'),
    (NULL, 'Hand', 'Ligament', 'Thumb CMC joint sprain'),
    (NULL, 'Hand', 'Joint sprain', 'PIP joint dislocation finger unknown'),
    (NULL, 'Hand', 'Joint sprain', 'Multiple PIP and/or DIP joint dislocations'),
    (NULL, 'Hand', 'Joint sprain', 'Complication of thumb joint dislocation'),
    (NULL, 'Hand', 'Joint sprain', 'MCP joint dislocation little finger'),
    (NULL, 'Hand', 'Joint sprain', 'MCP joint dislocation middle finger'),
    (NULL, 'Hand', 'Joint sprain', 'DIP joint dislocation finger unknown'),
    (NULL, 'Hand', 'Joint sprain', 'MCP joint dislocation of two or more fingers'),
    (NULL, 'Hand', 'Joint sprain', 'Dislocation of interphalangeal (IP) joint thumb'),
    (NULL, 'Hand', 'Joint sprain', 'Proximal interphalangeal (PIP) joint dislocation index finger'),
    (NULL, 'Hand', 'Joint sprain', 'PIP joint dislocation middle finger'),
    (NULL, 'Hand', 'Joint sprain', 'Dislocated metacarpophalangeal or interphalangeal joint'),
    (NULL, 'Hand', 'Joint sprain', 'PIP joint dislocation little finger'),
    (NULL, 'Hand', 'Joint sprain', 'MCP joint dislocation index finger'),
    (NULL, 'Hand', 'Joint sprain', 'Distal interphalangeal (DIP) joint dislocation index finger'),
    (NULL, 'Hand', 'Joint sprain', 'DIP joint dislocation middle finger'),
    (NULL, 'Hand', 'Joint sprain', 'Dislocation of MCP joint finger(s)'),
    (NULL, 'Hand', 'Joint sprain', 'Finger joint dislocation with volar plate injury'),
    (NULL, 'Hand', 'Joint sprain', 'Dislocation of MCP joint thumb'),
    (NULL, 'Hand', 'Joint sprain', 'DIP joint dislocation little finger'),
    (NULL, 'Hand', 'Joint sprain', 'Dislocation CMC joint thumb'),
    (NULL, 'Hand', 'Joint sprain', 'PIP joint dislocation ring finger'),
    (NULL, 'Hand', 'Joint sprain', 'DIP joint dislocation ring finger'),
    (NULL, 'Hand', 'Joint sprain', 'MCP joint dislocation ring finger'),
    (NULL, 'Hand', 'Chronic instability', 'Finger PIP or DIP joint instability'),
    (NULL, 'Hand', 'Chronic instability', 'Instability 1st CMC joint'),
    (NULL, 'Hand', 'Chronic instability', 'Complication of MCP joint sprain excl chronic instability'),
    (NULL, 'Hand', 'Chronic instability', 'Instability 1st MCP joint'),
    (NULL, 'Hand', 'Chronic instability', 'Complication of finger MCP joint sprain'),
    (NULL, 'Hand', 'Chronic instability', 'Interphalangeal joint instability of thumb'),
    (NULL, 'Hand', 'Chronic instability', 'Complication of PIP/DIP joint dislocation'),
    (NULL, 'Hand', 'Chronic instability', 'Finger MCP joint instability'),
    (NULL, 'Hand', 'Contusion/vascular', 'Thumbnail haematoma'),
    (NULL, 'Hand', 'Contusion/vascular', 'Thumb bruising/haematoma'),
    (NULL, 'Hand', 'Contusion/vascular', 'Fingernail haematoma'),
    (NULL, 'Hand', 'Laceration', 'Dorsal hand laceration'),
    (NULL, 'Hand', 'Laceration', 'Finger laceration'),
    (NULL, 'Hand', 'Laceration', 'Wrist and Hand Laceration/Abrasion'),
    (NULL, 'Hand', 'Laceration', 'Hand laceration'),
    (NULL, 'Hand', 'Laceration', 'Laceration of fingernail/nailbed'),
    (NULL, 'Hand', 'Laceration', 'Thumb laceration'),
    (NULL, 'Hand', 'Abrasion', 'Hand abrasion'),
    (NULL, 'Hand', 'Pain without tissue type specified', 'Other thumb pain not otherwise specified'),
    (NULL, 'Hand', 'Pain without tissue type specified', 'Chronic regional pain syndrome'),
    (NULL, 'Hand', 'Pain without tissue type specified', 'Other finger pain not otherwise specified'),
    (NULL, 'Hand', 'Unknown', 'Post hand surgery'),
    (NULL, 'Chest', 'Muscle injury', 'Chest muscle strain'),
    (NULL, 'Chest', 'Muscle contusion', 'Chest Wall Soft Tissue Bruising/Haematoma'),
    (NULL, 'Chest', 'Tendinopathy', 'Intercostal tendinopathy'),
    (NULL, 'Chest', 'Fracture', 'Chest Fracture(s)'),
    (NULL, 'Chest', 'Fracture', 'Fracture multiple ribs'),
    (NULL, 'Chest', 'Fracture', 'Fracture Middle rib (5 - 9)'),
    (NULL, 'Chest', 'Fracture', 'Fracture of costochondral margin'),
    (NULL, 'Chest', 'Fracture', 'Fracture lower rib (10 - 12'),
    (NULL, 'Chest', 'Fracture', 'Fractured rib(s)'),
    (NULL, 'Chest', 'Fracture', 'Fracture upper rib (1- 4)'),
    (NULL, 'Chest', 'Fracture', 'Sternal fracture'),
    (NULL, 'Chest', 'Bone stress injury', 'Stress fracture rib(s)'),
    (NULL, 'Chest', 'Bone contusion', 'Bruised ribs/chest wall'),
    (NULL, 'Chest', 'Bone contusion', 'Bruised sternum'),
    (NULL, 'Chest', 'Cartilage', 'Costal cartilage/costochondral joint injury'),
    (NULL, 'Chest', 'Cartilage', 'Costochondritis'),
    (NULL, 'Chest', 'Synovitis / capsulitis', 'Synovitis of Sternoclavicular joint'),
    (NULL, 'Chest', 'Synovitis / capsulitis', 'Synovitis of Chest Joint'),
    (NULL, 'Chest', 'Ligament', 'Sternoclavicular joint sprains'),
    (NULL, 'Chest', 'Ligament', 'Anterior sternoclavicular (S/C) joint sprain'),
    (NULL, 'Chest', 'Ligament', 'Posterior sternoclavicular joint sprain'),
    (NULL, 'Chest', 'Ligament', 'Chest Joint Sprains'),
    (NULL, 'Chest', 'Ligament', 'Costovertebral joint sprains'),
    (NULL, 'Chest', 'Joint sprain', 'Sternoclavicular joint dislocation'),
    (NULL, 'Chest', 'Joint sprain', 'Chest Dislocations'),
    (NULL, 'Chest', 'Joint sprain', 'Costochondral joint dislocation'),
    (NULL, 'Chest', 'Joint sprain', 'Posterior sternoclavicular joint dislocation'),
    (NULL, 'Chest', 'Chronic instability', 'Sternoclavicular joint instability'),
    (NULL, 'Chest', 'Chronic instability', 'Costochondral joint instability'),
    (NULL, 'Chest', 'Contusion/vascular', 'Breast haematoma/trauma'),
    (NULL, 'Chest', 'Laceration', 'Chest Wall laceration/Abrasion'),
    (NULL, 'Chest', 'Laceration', 'Truncal laceration/abrasion not requiring suturing'),
    (NULL, 'Chest', 'Abrasion', 'Chest wall abrasion (incl complications)'),
    (NULL, 'Chest', 'Organ trauma', 'Haemothorax'),
    (NULL, 'Chest', 'Organ trauma', 'Lung/Heart Traumatic Injury'),
    (NULL, 'Chest', 'Organ trauma', 'Pneumothorax'),
    (NULL, 'Chest', 'Pain without tissue type specified', 'Chest injury without tissue type specified'),
    (NULL, 'Chest', 'Unknown', 'Chest pain undiagnosed'),
    (NULL, 'Thoracic Spine', 'Muscle injury', 'Thoracic extensor muscle strain'),
    (NULL, 'Thoracic Spine', 'Muscle injury', 'Thoracic Muscle Strain/Spasm/Trigger Points'),
    (NULL, 'Thoracic Spine', 'Muscle contusion', 'Thoracic Soft Tissue Bruising/Haematoma'),
    (NULL, 'Thoracic Spine', 'Fracture', 'Thoracic Spine Fracture'),
    (NULL, 'Thoracic Spine', 'Fracture', 'Fracture transverse or posterior process thoracic spine'),
    (NULL, 'Thoracic Spine', 'Fracture', 'Fracture thoracic vertebral body'),
    (NULL, 'Thoracic Spine', 'Bone stress injury', 'Thoracic spine stress/compression fracture'),
    (NULL, 'Thoracic Spine', 'Bone contusion', 'Thoracic spine bone contusion'),
    (NULL, 'Thoracic Spine', 'Physis injury', 'Osteochondrosis Spine'),
    (NULL, 'Thoracic Spine', 'Physis injury', 'Scheuermanns disease'),
    (NULL, 'Thoracic Spine', 'Cartilage', 'Thoracic disc prolapse'),
    (NULL, 'Thoracic Spine', 'Arthritis', 'Thoracic spine Osteoarthritis (O/A)'),
    (NULL, 'Thoracic Spine', 'Arthritis', 'Facet joint O/A thoracic spine'),
    (NULL, 'Thoracic Spine', 'Synovitis / capsulitis', 'Inflammation/stiffness of costovertebral joints'),
    (NULL, 'Thoracic Spine', 'Ligament', 'Thoracic facet joint sprain'),
    (NULL, 'Thoracic Spine', 'Ligament', 'Thoracic spine Joint Injury'),
    (NULL, 'Thoracic Spine', 'Chronic instability', 'Costovertebral joint instability'),
    (NULL, 'Thoracic Spine', 'Laceration', 'Thoracic Laceration'),
    (NULL, 'Thoracic Spine', 'Abrasion', 'Thoracic abrasion (including infection)'),
    (NULL, 'Thoracic Spine', 'Pain without tissue type specified', 'Chronic thoracic functional pain'),
    (NULL, 'Thoracic Spine', 'Pain without tissue type specified', 'Thoracic Functional Pain'),
    (NULL, 'Thoracic Spine', 'Pain without tissue type specified', 'Thoracic muscle trigger points'),
    (NULL, 'Thoracic Spine', 'Unknown', 'Thoracic pain undiagnosed'),
    (NULL, 'Thoracic Spine', 'Unknown', 'Thoracic Pain/Injury not otherwise specified'),
    (NULL, 'Lumbar Spine', 'Muscle injury', 'Lumbar Spine muscle and Tendon Strain/Spasm/Trigger Points'),
    (NULL, 'Lumbar Spine', 'Muscle injury', 'Lumbar soreness or muscle spasm'),
    (NULL, 'Lumbar Spine', 'Muscle injury', 'Buttock Muscle Strain/Spasm/Trigger Points'),
    (NULL, 'Lumbar Spine', 'Muscle injury', 'Gluteal muscle strain'),
    (NULL, 'Lumbar Spine', 'Muscle injury', 'Buttock muscle soreness/trigger points'),
    (NULL, 'Lumbar Spine', 'Muscle injury', 'Piriformis muscle strain'),
    (NULL, 'Lumbar Spine', 'Muscle contusion', 'SIJ bruising/haematoma'),
    (NULL, 'Lumbar Spine', 'Muscle contusion', 'Buttock Soft Tissue Bruising/Haematoma'),
    (NULL, 'Lumbar Spine', 'Muscle contusion', 'Lumbar contusion/haematoma'),
    (NULL, 'Lumbar Spine', 'Tendinopathy', 'Piriformis tendinopathy/soreness'),
    (NULL, 'Lumbar Spine', 'Nerve injury', 'Lumbosacral Nerve root impingement due to foraminal stenosis bony and disc'),
    (NULL, 'Lumbar Spine', 'Nerve injury', 'Lumbar spinal injury'),
    (NULL, 'Lumbar Spine', 'Nerve injury', 'Lumbar nerve root impingement due to foraminal stenosis bony and disc'),
    (NULL, 'Lumbar Spine', 'Nerve injury', 'Buttock Nerve Injury'),
    (NULL, 'Lumbar Spine', 'Nerve injury', 'Lumbar spinal fracture with spinal cord/cauda equina injury'),
    (NULL, 'Lumbar Spine', 'Nerve injury', 'Piriformis syndrome (with sciatic nerve impingement)'),
    (NULL, 'Lumbar Spine', 'Nerve injury', 'Other lumbosacral nerve injury'),
    (NULL, 'Lumbar Spine', 'Nerve injury', 'Lumbar Spine Neurological Injury'),
    (NULL, 'Lumbar Spine', 'Nerve injury', 'Lumbosacral nerve stretch/traction injury'),
    (NULL, 'Lumbar Spine', 'Nerve injury', 'Lumbar Spinal canal stenosis'),
    (NULL, 'Lumbar Spine', 'Nerve injury', 'Lumbar spinal fracture with associated neurological injury'),
    (NULL, 'Lumbar Spine', 'Nerve injury', 'Pudendal Nerve Injury'),
    (NULL, 'Lumbar Spine', 'Fracture', 'Fractured sacrum'),
    (NULL, 'Lumbar Spine', 'Fracture', 'Lumbar pars interarticularis acute fracture'),
    (NULL, 'Lumbar Spine', 'Fracture', 'Complication of lumbar fracture'),
    (NULL, 'Lumbar Spine', 'Fracture', 'Lumbar pedicle fracture'),
    (NULL, 'Lumbar Spine', 'Fracture', 'Fractured ischium'),
    (NULL, 'Lumbar Spine', 'Fracture', 'Pelvic fracture(s)'),
    (NULL, 'Lumbar Spine', 'Fracture', 'Lumbar spinous process fracture'),
    (NULL, 'Lumbar Spine', 'Fracture', 'Fracture transverse process(es)'),
    (NULL, 'Lumbar Spine', 'Fracture', 'Lumbar spine vertebral body fracture'),
    (NULL, 'Lumbar Spine', 'Fracture', 'Lumbar Spine Fracture'),
    (NULL, 'Lumbar Spine', 'Fracture', 'Other lumbar spine fracture'),
    (NULL, 'Lumbar Spine', 'Fracture', 'Multiple lumbar spine fractures'),
    (NULL, 'Lumbar Spine', 'Bone stress injury', 'Lumbar stress reaction'),
    (NULL, 'Lumbar Spine', 'Bone stress injury', 'Stress fracture lumbar spine'),
    (NULL, 'Lumbar Spine', 'Bone stress injury', 'Stress fracture coccyx'),
    (NULL, 'Lumbar Spine', 'Bone stress injury', 'Pars stress fracture L4'),
    (NULL, 'Lumbar Spine', 'Bone stress injury', 'Pars stress fracture L1 - L3'),
    (NULL, 'Lumbar Spine', 'Bone stress injury', 'Stress fracture ischium'),
    (NULL, 'Lumbar Spine', 'Bone stress injury', 'Spondylolisthesis lumbar'),
    (NULL, 'Lumbar Spine', 'Bone stress injury', 'Other lumbar spine stress fracture'),
    (NULL, 'Lumbar Spine', 'Bone stress injury', 'Stress fracture sacrum'),
    (NULL, 'Lumbar Spine', 'Bone stress injury', 'Multiple (incl bilateral) pars stress fractures'),
    (NULL, 'Lumbar Spine', 'Bone stress injury', 'Stress fracture ilium'),
    (NULL, 'Lumbar Spine', 'Bone stress injury', 'Pars interarticularis stress fracture'),
    (NULL, 'Lumbar Spine', 'Bone stress injury', 'Lumbar pedicle stress fracture'),
    (NULL, 'Lumbar Spine', 'Bone stress injury', 'Other stress fracture pelvis'),
    (NULL, 'Lumbar Spine', 'Bone stress injury', 'Pars stress fracture L5'),
    (NULL, 'Lumbar Spine', 'Bone contusion', 'Lumbar spine/buttock bone contusion'),
    (NULL, 'Lumbar Spine', 'Physis injury', 'Lumbar Spine Joint Injury'),
    (NULL, 'Lumbar Spine', 'Cartilage', 'Lumbar disc prolapse'),
    (NULL, 'Lumbar Spine', 'Cartilage', 'Lumbar disc annular tear'),
    (NULL, 'Lumbar Spine', 'Cartilage', 'Disc degeneration'),
    (NULL, 'Lumbar Spine', 'Cartilage', 'Disc prolapse/disruption'),
    (NULL, 'Lumbar Spine', 'Arthritis', 'Facet joint O/A lumbosacral spine'),
    (NULL, 'Lumbar Spine', 'Arthritis', 'Degenerative L5/S1 disc disease'),
    (NULL, 'Lumbar Spine', 'Arthritis', 'Osteoarthritis Lumbosacral spine'),
    (NULL, 'Lumbar Spine', 'Arthritis', 'Degenerative disc disease multiple levels lumbar spine'),
    (NULL, 'Lumbar Spine', 'Arthritis', 'Degenerative L4/L5 disc disease'),
    (NULL, 'Lumbar Spine', 'Ligament', 'Sacroiliac joint sprain'),
    (NULL, 'Lumbar Spine', 'Ligament', 'Lumbar facet joint sprain'),
    (NULL, 'Lumbar Spine', 'Ligament', 'Spinal joint sprain'),
    (NULL, 'Lumbar Spine', 'Ligament', 'Sacrococcygeal joint injury/pain'),
    (NULL, 'Lumbar Spine', 'Ligament', 'Iliolumbar Ligament pain'),
    (NULL, 'Lumbar Spine', 'Ligament', 'Lumbar region ligament sprain'),
    (NULL, 'Lumbar Spine', 'Chronic instability', 'Lumbar Instability'),
    (NULL, 'Lumbar Spine', 'Chronic instability', 'Spondylolisthesis any Level'),
    (NULL, 'Lumbar Spine', 'Chronic instability', 'Grade 2-3 Spondylolisthesis lumbar spine'),
    (NULL, 'Lumbar Spine', 'Chronic instability', 'Lumbosacral instability'),
    (NULL, 'Lumbar Spine', 'Chronic instability', 'Retrolisthesis lumbar spine'),
    (NULL, 'Lumbar Spine', 'Chronic instability', 'Grade 4 Spondylolisthesis lumbar spine'),
    (NULL, 'Lumbar Spine', 'Chronic instability', 'Sacroiliac Joint Instability'),
    (NULL, 'Lumbar Spine', 'Laceration', 'Complication of lumbosacral laceration incl infection'),
    (NULL, 'Lumbar Spine', 'Laceration', 'Pelvic/Buttock Laceration'),
    (NULL, 'Lumbar Spine', 'Laceration', 'Lumbar Laceration'),
    (NULL, 'Lumbar Spine', 'Abrasion', 'Buttock abrasion incl pressure sores'),
    (NULL, 'Lumbar Spine', 'Pain without tissue type specified', 'Chronic lumbar functional pain'),
    (NULL, 'Lumbar Spine', 'Pain without tissue type specified', 'Sacroiliac Joint Injury/Pain'),
    (NULL, 'Lumbar Spine', 'Unknown', 'Lumbar pain/injury not otherwise specified'),
    (NULL, 'Lumbar Spine', 'Unknown', 'Lumbar pain with hamstring referral'),
    (NULL, 'Lumbar Spine', 'Unknown', 'Lumbar pain non-specific'),
    (NULL, 'Lumbar Spine', 'Unknown', 'Buttock pain undiagnosed'),
    (NULL, 'Lumbar Spine', 'Unknown', 'Buttock Pain not otherwise specified'),
    (NULL, 'Abdomen', 'Muscle injury', 'Transversus abdominis muscle strain'),
    (NULL, 'Abdomen', 'Muscle injury', 'Rectus abdominis trigger points/spasm'),
    (NULL, 'Abdomen', 'Muscle injury', 'Truncal Muscle Strain'),
    (NULL, 'Abdomen', 'Muscle injury', 'Truncal Muscle Trigger Points/Spasm'),
    (NULL, 'Abdomen', 'Muscle injury', 'Winded'),
    (NULL, 'Abdomen', 'Muscle injury', 'Abdominal oblique muscle strain'),
    (NULL, 'Abdomen', 'Muscle injury', 'Abdominal muscle soreness or spasm'),
    (NULL, 'Abdomen', 'Muscle contusion', 'Abdominopelvic Soft Tissue Bruising/Haematoma'),
    (NULL, 'Abdomen', 'Tendinopathy', 'Divarication of rectus abdominis'),
    (NULL, 'Abdomen', 'Tendinopathy', 'Umbilical Hernia'),
    (NULL, 'Abdomen', 'Tendinopathy', 'Abdominal tendon insertion strain'),
    (NULL, 'Abdomen', 'Tendinopathy', 'Direct inguinal hernia'),
    (NULL, 'Abdomen', 'Tendinopathy', 'Sports hernia/abdominal tendinopathy'),
    (NULL, 'Abdomen', 'Tendinopathy', 'Costolliac impingement'),
    (NULL, 'Abdomen', 'Tendinopathy', 'Abdominal tendon Injury'),
    (NULL, 'Abdomen', 'Tendinopathy', 'Rectus abdominus tendinopathy'),
    (NULL, 'Abdomen', 'Tendinopathy', 'Abdominal tendon insertion injury'),
    (NULL, 'Abdomen', 'Tendon rupture', 'Abdominal tendon insertion rupture'),
    (NULL, 'Abdomen', 'Laceration', 'Truncal laceration requiring suturing'),
    (NULL, 'Abdomen', 'Laceration', 'Truncal Laceration/Abrasion'),
    (NULL, 'Abdomen', 'Abrasion', 'Complication of abrasion to trunk - including infection'),
    (NULL, 'Abdomen', 'Organ trauma', 'Abdominal organ Injury'),
    (NULL, 'Abdomen', 'Organ trauma', 'Spleen trauma'),
    (NULL, 'Abdomen', 'Organ trauma', 'Pancreatic trauma'),
    (NULL, 'Abdomen', 'Organ trauma', 'Trunk and Abdominal Injury'),
    (NULL, 'Abdomen', 'Organ trauma', 'Other organ trauma not otherwise specified'),
    (NULL, 'Abdomen', 'Organ trauma', 'Bladder trauma'),
    (NULL, 'Abdomen', 'Organ trauma', 'Intestinal trauma'),
    (NULL, 'Abdomen', 'Organ trauma', 'Kidney trauma'),
    (NULL, 'Abdomen', 'Organ trauma', 'Liver trauma'),
    (NULL, 'Abdomen', 'Organ trauma', 'Multiple organ trauma'),
    (NULL, 'Abdomen', 'Pain without tissue type specified', 'Abdominal muscle cramps'),
    (NULL, 'Abdomen', 'Unknown', 'Abdominal pain undiagnosed'),
    (NULL, 'Abdomen', 'Unknown', 'Abdominal pain not otherwise specified'),
    (NULL, 'Groin/hip', 'Muscle injury', 'Proximal adductor trigger points'),
    (NULL, 'Groin/hip', 'Muscle injury', 'Groin soreness or trigger points'),
    (NULL, 'Groin/hip', 'Muscle injury', 'Psoas muscle strain/tear'),
    (NULL, 'Groin/hip', 'Muscle injury', 'Rectus abdominus strain'),
    (NULL, 'Groin/hip', 'Muscle injury', 'Hip and Groin Muscle Strain/Tear'),
    (NULL, 'Groin/hip', 'Muscle injury', 'Soreness/trigger points iliopsoas'),
    (NULL, 'Groin/hip', 'Muscle injury', 'Hip flexor muscle strain'),
    (NULL, 'Groin/hip', 'Muscle injury', 'Iliopsoas muscle strain/tear'),
    (NULL, 'Groin/hip', 'Muscle contusion', 'contusion/haematoma, hip region'),
    (NULL, 'Groin/hip', 'Muscle contusion', 'Labial bruising/haematoma'),
    (NULL, 'Groin/hip', 'Muscle contusion', 'Other hip/groin bruising/haematoma'),
    (NULL, 'Groin/hip', 'Tendinopathy', 'Adductor longus tendon injury'),
    (NULL, 'Groin/hip', 'Tendinopathy', 'Iliopsoas tendon rupture'),
    (NULL, 'Groin/hip', 'Tendinopathy', 'Adductor origin tendinopathy'),
    (NULL, 'Groin/hip', 'Tendinopathy', 'Iliopsoas tendinopathy'),
    (NULL, 'Groin/hip', 'Tendinopathy', 'Sportsman''s hernia'),
    (NULL, 'Groin/hip', 'Tendinopathy', 'Indirect inguinal hernia'),
    (NULL, 'Groin/hip', 'Tendinopathy', 'Rectus femoris tendon strain'),
    (NULL, 'Groin/hip', 'Tendinopathy', 'Unspecified or multiple adductor tendon injury'),
    (NULL, 'Groin/hip', 'Tendinopathy', 'Adductor magnus tendon injury'),
    (NULL, 'Groin/hip', 'Tendinopathy', 'Iliopsoas tendon injury'),
    (NULL, 'Groin/hip', 'Tendinopathy', 'Femoral hernia'),
    (NULL, 'Groin/hip', 'Tendinopathy', 'Adductor magnus tendon strain'),
    (NULL, 'Groin/hip', 'Tendinopathy', 'Rectus femoris tendon injury'),
    (NULL, 'Groin/hip', 'Tendinopathy', 'Snapping psoas tendon'),
    (NULL, 'Groin/hip', 'Tendinopathy', 'Sartorius tendon strain'),
    (NULL, 'Groin/hip', 'Tendinopathy', 'Sartorius tendinopathy'),
    (NULL, 'Groin/hip', 'Tendinopathy', 'Hip and Groin Tendon Injuries'),
    (NULL, 'Groin/hip', 'Tendinopathy', 'Iliopsoas tendinopathy/bursitis'),
    (NULL, 'Groin/hip', 'Tendinopathy', 'Iliopsoas tendon strain'),
    (NULL, 'Groin/hip', 'Tendinopathy', 'Adductor longus tendon strain'),
    (NULL, 'Groin/hip', 'Tendinopathy', 'Adductor magnus tendinopathy'),
    (NULL, 'Groin/hip', 'Tendinopathy', 'Abdominal tendon insertion tendinopathy'),
    (NULL, 'Groin/hip', 'Tendon rupture', 'Rectus femoris origin tendon rupture'),
    (NULL, 'Groin/hip', 'Tendon rupture', 'Adductor longus tendon rupture'),
    (NULL, 'Groin/hip', 'Tendon rupture', 'Sartorius tendon rupture'),
    (NULL, 'Groin/hip', 'Tendon rupture', 'Adductor magnus tendon rupture'),
    (NULL, 'Groin/hip', 'Nerve injury', 'Genitofemoral nerve entrapment'),
    (NULL, 'Groin/hip', 'Nerve injury', 'Groin Neurovascular Injuries'),
    (NULL, 'Groin/hip', 'Nerve injury', 'Obturator nerve entrapment'),
    (NULL, 'Groin/hip', 'Nerve injury', 'Thigh Neurological Injury'),
    (NULL, 'Groin/hip', 'Nerve injury', 'Ilioinguinal nerve entrapment'),
    (NULL, 'Groin/hip', 'Nerve injury', 'Nerve Entrapment Groin'),
    (NULL, 'Groin/hip', 'Fracture', 'Fracture pubic ramus'),
    (NULL, 'Groin/hip', 'Fracture', 'Acetabular fracture'),
    (NULL, 'Groin/hip', 'Fracture', 'Hip/Groin Fractures'),
    (NULL, 'Groin/hip', 'Fracture', 'Fracture inferior pubic ramus'),
    (NULL, 'Groin/hip', 'Fracture', 'Fractured neck of femur'),
    (NULL, 'Groin/hip', 'Fracture', 'Fractured Ilium'),
    (NULL, 'Groin/hip', 'Fracture', 'Fractured coccyx'),
    (NULL, 'Groin/hip', 'Fracture', 'Femoral fracture'),
    (NULL, 'Groin/hip', 'Fracture', 'Fracture superior pubic ramus'),
    (NULL, 'Groin/hip', 'Bone stress injury', 'Stress fracture inferior pubic ramus'),
    (NULL, 'Groin/hip', 'Bone stress injury', 'Stress fracture pelvic bone'),
    (NULL, 'Groin/hip', 'Bone stress injury', 'Stress fracture inferior cortex femoral neck'),
    (NULL, 'Groin/hip', 'Bone stress injury', 'Stress fracture superior cortex femoral neck'),
    (NULL, 'Groin/hip', 'Bone stress injury', 'Multiple stress fractures pelvis'),
    (NULL, 'Groin/hip', 'Bone stress injury', 'Femoral neck stress fracture'),
    (NULL, 'Groin/hip', 'Bone stress injury', 'Pelvic stress fracture'),
    (NULL, 'Groin/hip', 'Bone stress injury', 'Osteitis pubis'),
    (NULL, 'Groin/hip', 'Bone stress injury', 'Stress fracture through femoral neck (both cortices)'),
    (NULL, 'Groin/hip', 'Bone stress injury', 'Hip/Groin Stress Fracture'),
    (NULL, 'Groin/hip', 'Bone contusion', 'Groin/hip bone contusion'),
    (NULL, 'Groin/hip', 'Avascular necrosis', 'Avascular necrosis femoral head'),
    (NULL, 'Groin/hip', 'Avascular necrosis', 'Perthes disease'),
    (NULL, 'Groin/hip', 'Avascular necrosis', 'Hip avascular necrosis'),
    (NULL, 'Groin/hip', 'Physis injury', 'Apophysitis/avulsion fracture ischial tuberosity'),
    (NULL, 'Groin/hip', 'Physis injury', 'Apophysitis/avulsion fracture Anterior Inferior Iliac Spine (AIIS)'),
    (NULL, 'Groin/hip', 'Physis injury', 'Slipped capital femoral epiphysis'),
    (NULL, 'Groin/hip', 'Physis injury', 'Other apophysitis/avulsion fracture groin/hip'),
    (NULL, 'Groin/hip', 'Physis injury', 'Osteochondroses of hip joint'),
    (NULL, 'Groin/hip', 'Physis injury', 'Traction injury to apophysis at buttock and pelvis'),
    (NULL, 'Groin/hip', 'Physis injury', 'Traction injury to apophysis at groin/hip joint'),
    (NULL, 'Groin/hip', 'Physis injury', 'Apophysitis/avulsion fracture Anterior Superior Iliac Spine (ASIS)'),
    (NULL, 'Groin/hip', 'Physis injury', 'Apophysitis/avulsion fracture iliac crest'),
    (NULL, 'Groin/hip', 'Cartilage', 'Hip Joint Chondral/Osteochondral Injury'),
    (NULL, 'Groin/hip', 'Cartilage', 'Hip joint chondral lesion'),
    (NULL, 'Groin/hip', 'Cartilage', 'Labral tear, hip joint'),
    (NULL, 'Groin/hip', 'Arthritis', 'Hip joint osteoarthritis (O/A)'),
    (NULL, 'Groin/hip', 'Arthritis', 'Hip/Groin Arthritis'),
    (NULL, 'Groin/hip', 'Synovitis / capsulitis', 'Hip Joint Inflammation/Synovitis/Other Biomechanical Lesion'),
    (NULL, 'Groin/hip', 'Synovitis / capsulitis', 'Synovitis of hip joint'),
    (NULL, 'Groin/hip', 'Bursitis', 'Trochanteric bursitis'),
    (NULL, 'Groin/hip', 'Ligament', 'Hip joint sprain/jar'),
    (NULL, 'Groin/hip', 'Joint sprain', 'Hip Joint Dislocation'),
    (NULL, 'Groin/hip', 'Chronic instability', 'Pubic symphysis instability'),
    (NULL, 'Groin/hip', 'Chronic instability', 'Instability of Hip joint'),
    (NULL, 'Groin/hip', 'Contusion/vascular', 'Exercise-related iliac artery flow limitation'),
    (NULL, 'Groin/hip', 'Contusion/vascular', 'Vascular Injury Hip Region'),
    (NULL, 'Groin/hip', 'Laceration', 'Complication of laceration including infection'),
    (NULL, 'Groin/hip', 'Laceration', 'Hip and Groin Laceration'),
    (NULL, 'Groin/hip', 'Abrasion', 'Groin/hip abrasion'),
    (NULL, 'Groin/hip', 'Organ trauma', 'Ruptured penis/urethra'),
    (NULL, 'Groin/hip', 'Organ trauma', 'Groin Organ Damage'),
    (NULL, 'Groin/hip', 'Organ trauma', 'Testicular rupture'),
    (NULL, 'Groin/hip', 'Organ trauma', 'Pelvic Organ Injury'),
    (NULL, 'Groin/hip', 'Organ trauma', 'Testicular/scrotal contusion/haematoma'),
    (NULL, 'Groin/hip', 'Organ trauma', 'Penile injury'),
    (NULL, 'Groin/hip', 'Pain without tissue type specified', 'Chronic non specific /functional groin pain'),
    (NULL, 'Groin/hip', 'Pain without tissue type specified', 'Other Stress/Overuse Injury Hip and Groin'),
    (NULL, 'Groin/hip', 'Unknown', 'Post hip/groin Surgery'),
    (NULL, 'Groin/hip', 'Unknown', 'Clicking hip'),
    (NULL, 'Groin/hip', 'Unknown', 'Groin pain undiagnosed'),
    (NULL, 'Groin/hip', 'Unknown', 'Hip/Groin Pain Not otherwise specified'),
    (NULL, 'Groin/hip', 'Unknown', 'Pelvic/Buttock Pain not otherwise specified'),
    (NULL, 'Thigh', 'Muscle injury', 'Adductor muscle rupture/grade 3 strain'),
    (NULL, 'Thigh', 'Muscle injury', 'Thigh Muscle strain/Spasm/Trigger Points'),
    (NULL, 'Thigh', 'Muscle injury', 'Adductor longus strain'),
    (NULL, 'Thigh', 'Muscle injury', 'Adductor muscle cramping during exercise'),
    (NULL, 'Thigh', 'Muscle injury', 'Quadriceps strain/tear'),
    (NULL, 'Thigh', 'Muscle injury', 'Hamstring strain/tear'),
    (NULL, 'Thigh', 'Muscle injury', 'Biceps femoris strain grade 1 - 2'),
    (NULL, 'Thigh', 'Muscle injury', 'Rectus femoris strain'),
    (NULL, 'Thigh', 'Muscle injury', 'Thigh muscle trigger points'),
    (NULL, 'Thigh', 'Muscle injury', 'Thigh muscle wasting'),
    (NULL, 'Thigh', 'Muscle injury', 'Quadriceps wasting'),
    (NULL, 'Thigh', 'Muscle injury', 'Rectus femoris trigger points'),
    (NULL, 'Thigh', 'Muscle injury', 'Gluteus medius/minimus strain'),
    (NULL, 'Thigh', 'Muscle injury', 'Quadricep cramping during exercise'),
    (NULL, 'Thigh', 'Muscle injury', 'Grade 3 hamstring strain'),
    (NULL, 'Thigh', 'Muscle injury', 'Semimembranosis/tendinosis strain (grade 1 - 2)'),
    (NULL, 'Thigh', 'Muscle injury', 'Adductor magnus strain'),
    (NULL, 'Thigh', 'Muscle injury', 'Thigh muscle cramping during exercise'),
    (NULL, 'Thigh', 'Muscle injury', 'Rectus femoris rupture'),
    (NULL, 'Thigh', 'Muscle injury', 'Hamstring cramping during exercise'),
    (NULL, 'Thigh', 'Muscle injury', 'Distal adductor strain'),
    (NULL, 'Thigh', 'Muscle injury', 'Other quadricep strain'),
    (NULL, 'Thigh', 'Muscle injury', 'Back referred hamstring tightness'),
    (NULL, 'Thigh', 'Muscle injury', 'Gluteus maximus strain'),
    (NULL, 'Thigh', 'Muscle injury', 'Lateral hamstring trigger points'),
    (NULL, 'Thigh', 'Muscle injury', 'Back referred muscle tightness'),
    (NULL, 'Thigh', 'Muscle contusion', 'Acute arterial bleed thigh'),
    (NULL, 'Thigh', 'Muscle contusion', 'Iliotibial band haematoma'),
    (NULL, 'Thigh', 'Muscle contusion', 'Thigh muscle haematoma'),
    (NULL, 'Thigh', 'Muscle contusion', 'Other thigh soft tissue bruising/haematoma not otherwise specified'),
    (NULL, 'Thigh', 'Muscle contusion', 'Adductor muscle haematoma'),
    (NULL, 'Thigh', 'Muscle contusion', 'Myositis ossificans thigh'),
    (NULL, 'Thigh', 'Muscle contusion', 'Bruising/haematoma iliac crest/gluteus medius'),
    (NULL, 'Thigh', 'Muscle contusion', 'Hamstring muscle haematoma'),
    (NULL, 'Thigh', 'Muscle contusion', 'Contusion/haematoma of thigh'),
    (NULL, 'Thigh', 'Muscle contusion', 'Quadriceps muscle haematoma'),
    (NULL, 'Thigh', 'Muscle compartment syndrome', 'Compartment Syndrome of Thigh'),
    (NULL, 'Thigh', 'Tendinopathy', 'Hamstring origin tendinopathy'),
    (NULL, 'Thigh', 'Tendinopathy', 'Gluteus med/min tendinopathy'),
    (NULL, 'Thigh', 'Tendinopathy', 'Rectus femoris origin tendinopathy'),
    (NULL, 'Thigh', 'Tendinopathy', 'Thigh Tendon Injuries'),
    (NULL, 'Thigh', 'Tendinopathy', 'Gluteal tendinopathy/enthesopathy'),
    (NULL, 'Thigh', 'Tendinopathy', 'Hamstring tendinopathy with ischial bursitis'),
    (NULL, 'Thigh', 'Tendinopathy', 'Tenoperiostitis of Thigh'),
    (NULL, 'Thigh', 'Tendinopathy', 'Sartorius tendon injury'),
    (NULL, 'Thigh', 'Tendon rupture', 'Hamstring origin tendon rupture'),
    (NULL, 'Thigh', 'Tendon rupture', 'Hamstring tendon injury'),
    (NULL, 'Thigh', 'Tendon rupture', 'Gluteus med/min tendon rupture'),
    (NULL, 'Thigh', 'Nerve injury', 'Nerve entrapment in thigh'),
    (NULL, 'Thigh', 'Nerve injury', 'Lateral cutaneous nerve of thigh entrapment'),
    (NULL, 'Thigh', 'Fracture', 'Fractured femoral shaft'),
    (NULL, 'Thigh', 'Fracture', 'Thigh Fractures'),
    (NULL, 'Thigh', 'Bone stress injury', 'Femoral shaft stress fracture'),
    (NULL, 'Thigh', 'Bone stress injury', 'Thigh Stress Fractures'),
    (NULL, 'Thigh', 'Bone contusion', 'Femur bone contusion'),
    (NULL, 'Thigh', 'Physis injury', 'Thigh region physis injury'),
    (NULL, 'Thigh', 'Laceration', 'Thigh Laceration/Abrasion'),
    (NULL, 'Thigh', 'Laceration', 'Complication of laceration incl. infection'),
    (NULL, 'Thigh', 'Abrasion', 'Thigh abrasion'),
    (NULL, 'Thigh', 'Stump injury', 'Stump trauma thigh'),
    (NULL, 'Thigh', 'Stump injury', 'Infection of stump thigh'),
    (NULL, 'Thigh', 'Pain without tissue type specified', 'Thigh pain without tissue type specified'),
    (NULL, 'Thigh', 'Unknown', 'Thigh Pain Not otherwise specified'),
    (NULL, 'Thigh', 'Unknown', 'Thigh pain/Injury Not otherwise specified'),
    (NULL, 'Thigh', 'Unknown', 'Thigh pain undiagnosed'),
    (NULL, 'Thigh', 'Unknown', 'Other stress/Overuse Injuries to Thigh'),
    (NULL, 'Knee', 'Muscle injury', 'Popliteus muscle strain'),
    (NULL, 'Knee', 'Muscle injury', 'Knee Muscle Strain/Spasm/Trigger Points'),
    (NULL, 'Knee', 'Muscle contusion', 'Other soft tissue bruising/haematoma knee'),
    (NULL, 'Knee', 'Muscle contusion', 'Distal quadricep haematoma'),
    (NULL, 'Knee', 'Tendinopathy', 'Patellar Tendon Injury'),
    (NULL, 'Knee', 'Tendinopathy', 'Lateral gastroc tendinopathy knee'),
    (NULL, 'Knee', 'Tendinopathy', 'Medial hamstring insertion tendonitis/pes anserinus bursitis'),
    (NULL, 'Knee', 'Tendinopathy', 'Quadriceps tendon injury'),
    (NULL, 'Knee', 'Tendinopathy', 'Lateral hamstring insertion tendonitis'),
    (NULL, 'Knee', 'Tendinopathy', 'Popliteus tendinopathy/strain'),
    (NULL, 'Knee', 'Tendinopathy', 'Insertional Patellar tendon pathology, incl intratendon ossicle'),
    (NULL, 'Knee', 'Tendinopathy', 'Medial hamstring tendon strain at knee'),
    (NULL, 'Knee', 'Tendinopathy', 'Patellar tendinopathy'),
    (NULL, 'Knee', 'Tendinopathy', 'Knee Tendon Injury'),
    (NULL, 'Knee', 'Tendinopathy', 'Quadriceps tendinopathy +/- suprapatellar bursitis'),
    (NULL, 'Knee', 'Tendinopathy', 'Medial gastroc tendinopathy knee'),
    (NULL, 'Knee', 'Tendinopathy', 'Lateral hamstring tendon strain at knee'),
    (NULL, 'Knee', 'Tendinopathy', 'Gastrocnemius tendon injury'),
    (NULL, 'Knee', 'Tendinopathy', 'Iliotibial band syndrome'),
    (NULL, 'Knee', 'Tendon rupture', 'Medial hamstring tendon rupture'),
    (NULL, 'Knee', 'Tendon rupture', 'Quadriceps tendon rupture'),
    (NULL, 'Knee', 'Tendon rupture', 'Hamstring tendon rupture'),
    (NULL, 'Knee', 'Tendon rupture', 'Lateral hamstring tendon rupture at knee'),
    (NULL, 'Knee', 'Tendon rupture', 'Patellar tendon rupture'),
    (NULL, 'Knee', 'Fracture', 'Knee Fractures'),
    (NULL, 'Knee', 'Fracture', 'Proximal tibial fracture'),
    (NULL, 'Knee', 'Fracture', 'Distal femoral fracture'),
    (NULL, 'Knee', 'Fracture', 'Patella fracture'),
    (NULL, 'Knee', 'Fracture', 'Intraarticular femoral fracture'),
    (NULL, 'Knee', 'Fracture', 'Intraarticular tibial fracture'),
    (NULL, 'Knee', 'Bone stress injury', 'Distal femoral stress fracture'),
    (NULL, 'Knee', 'Bone stress injury', 'Patellar stress fracture'),
    (NULL, 'Knee', 'Bone stress injury', 'Knee Stress Fracture'),
    (NULL, 'Knee', 'Bone contusion', 'Knee bone contusion'),
    (NULL, 'Knee', 'Physis injury', 'Epiphysitis of medial tibial plateau (Blount''s Disease)'),
    (NULL, 'Knee', 'Physis injury', 'Osgood-Schlatter syndrome'),
    (NULL, 'Knee', 'Physis injury', 'Patella symptoms related to bipartite patella'),
    (NULL, 'Knee', 'Physis injury', 'Traction injury to apophysis at knee'),
    (NULL, 'Knee', 'Physis injury', 'Apophysitis/avulsion fracture distal pole patella/Sinding Larsen Johansson Syndrome (SLJS)'),
    (NULL, 'Knee', 'Cartilage', 'Lateral meniscal cyst'),
    (NULL, 'Knee', 'Cartilage', 'Knee cartilage injury with loose bodies'),
    (NULL, 'Knee', 'Cartilage', 'Mixed osteochondral and meniscal injury'),
    (NULL, 'Knee', 'Cartilage', 'Degenerative meniscal tear'),
    (NULL, 'Knee', 'Cartilage', 'Medial and lateral meniscal tears'),
    (NULL, 'Knee', 'Cartilage', 'Osteochondritis dissecans (OCD) patella'),
    (NULL, 'Knee', 'Cartilage', 'Osteochondrosis of knee'),
    (NULL, 'Knee', 'Cartilage', 'Medial meniscal tear'),
    (NULL, 'Knee', 'Cartilage', 'Knee joint cartilage injury (unspecified)'),
    (NULL, 'Knee', 'Cartilage', 'Lateral femoral condyle osteochondral injury'),
    (NULL, 'Knee', 'Cartilage', 'Knee articular cartilage damage'),
    (NULL, 'Knee', 'Cartilage', 'Patellofemoral osteochondral injury'),
    (NULL, 'Knee', 'Cartilage', 'Tibial osteochondral injury'),
    (NULL, 'Knee', 'Cartilage', 'Patellofemoral joint chondral pain'),
    (NULL, 'Knee', 'Cartilage', 'Osteochondritis dissecans (OCD) medial or lateral femoral condyle'),
    (NULL, 'Knee', 'Cartilage', 'Medial femoral condyle osteochondral injury'),
    (NULL, 'Knee', 'Cartilage', 'Lateral meniscal tear'),
    (NULL, 'Knee', 'Arthritis', 'Post arthroplasty knee'),
    (NULL, 'Knee', 'Arthritis', 'Patellofemoral osteoarthritis'),
    (NULL, 'Knee', 'Arthritis', 'Medial compartment osteoarthritis knee'),
    (NULL, 'Knee', 'Arthritis', 'Lateral compartment osteoarthritis knee'),
    (NULL, 'Knee', 'Arthritis', 'Knee osteoarthritis (O/A)'),
    (NULL, 'Knee', 'Arthritis', 'Bi- or tri-compartmental osteoarthritis'),
    (NULL, 'Knee', 'Synovitis / capsulitis', 'Knee Joint synovitis'),
    (NULL, 'Knee', 'Synovitis / capsulitis', 'Hoffa''s fat pad impingement')
ON CONFLICT (region, injury_type, diagnosis) WHERE organization_id IS NULL DO NOTHING;

-- Finished seeding 999 global records (deduplicated from 1000).