import express from 'express';
import nodemailer from 'nodemailer';
import { db, autoAllocateStaffServices } from './db.js';
import { requireAuth } from './middleware.js';

const router = express.Router();

const transporter = nodemailer.createTransport({
  host: process.env.SMTP_HOST || 'smtp.email.ap-mumbai-1.oci.oraclecloud.com',
  port: parseInt(process.env.SMTP_PORT || '587', 10),
  secure: process.env.SMTP_SECURE === 'true',
  auth: {
    user: process.env.SMTP_USER,
    pass: process.env.SMTP_PASS,
  },
});

function generateActivityTrackerHTML(date, staffMetrics) {
  const rowsHtml = staffMetrics.map(s => {
    const activeStr = s.activeMinutes > 0 ? `${Math.floor(s.activeMinutes/60)}h ${s.activeMinutes%60}m (${s.activeMinutes} mins)` : 'No Activity';
    const sessionsStr = s.sessionsCount > 0 ? `${s.sessionsCount} Sessions` : 'No Activity';
    const regStr = s.registrationsCount > 0 ? `${s.registrationsCount} Registrations` : 'No Activity';

    return `
      <tr style="border-bottom: 1px solid #e2e8f0;">
        <td style="padding: 10px; font-weight: bold; color: #0f172a;">${s.name}<br/><span style="font-size: 11px; color: #64748b;">${s.profession || s.role}</span></td>
        <td style="padding: 10px; text-align: center; color: ${s.activeMinutes > 0 ? '#10b981' : '#94a3b8'}; font-weight: bold;">${activeStr}</td>
        <td style="padding: 10px; text-align: center; color: ${s.sessionsCount > 0 ? '#8b5cf6' : '#94a3b8'}; font-weight: bold;">${sessionsStr}</td>
        <td style="padding: 10px; text-align: center; color: ${s.registrationsCount > 0 ? '#f59e0b' : '#94a3b8'}; font-weight: bold;">${regStr}</td>
      </tr>
    `;
  }).join('');

  return `
    <div style="font-family: Arial, sans-serif; max-width: 650px; margin: 0 auto; border: 1px solid #e2e8f0; border-radius: 12px; padding: 24px; background: #ffffff;">
      <h2 style="color: #0d9488; margin-top: 0;">Center for Spine & Sports Health (CSSH)</h2>
      <h3 style="color: #0f172a; margin-bottom: 4px;">Staff Activity Tracker Daily Summary</h3>
      <p style="color: #64748b; font-size: 13px; margin-top: 0;">Report Date: <strong>${date}</strong></p>
      
      <table style="width: 100%; border-collapse: collapse; margin-top: 16px; font-size: 13px;">
        <thead>
          <tr style="background: #f8fafc; border-bottom: 2px solid #cbd5e1; text-transform: uppercase; font-size: 11px; color: #475569;">
            <th style="padding: 10px; text-align: left;">Staff Member</th>
            <th style="padding: 10px; text-align: center;">Active Time</th>
            <th style="padding: 10px; text-align: center;">Sessions</th>
            <th style="padding: 10px; text-align: center;">Registrations</th>
          </tr>
        </thead>
        <tbody>
          ${rowsHtml}
        </tbody>
      </table>
      <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 24px 0;" />
      <p style="font-size: 11px; color: #94a3b8; text-align: center;">Automated Activity Report generated by ISHPO System.</p>
    </div>
  `;
}

// GET current user profile
router.get('/profile', requireAuth, async (req, res) => {
    try {
        const result = await db.query('SELECT * FROM profiles WHERE id = $1', [req.user.id]);
        if (result.rows.length === 0) return res.status(404).json({ error: 'Profile not found' });
        res.json(result.rows[0]);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

// GET Staff Activity Tracker & Console Activity Metrics
const getActivityMetricsHandler = async (req, res) => {
    try {
        const { date } = req.query;
        const targetDate = date || new Date().toISOString().split('T')[0];

        // Fetch all staff members (excluding pure client/athlete accounts)
        let staffQuery = `
            SELECT p.id, p.first_name, p.last_name, p.profession, u.role, u.email
            FROM profiles p
            JOIN users u ON p.id = u.id
            WHERE u.role NOT IN ('client', 'athlete')
            ORDER BY p.first_name ASC
        `;

        const staffRes = await db.query(staffQuery);
        const staffList = staffRes.rows;

        // Fetch actual application usage activity (active seconds spent on console)
        const appActivityRes = await db.query(
            `SELECT user_id, active_seconds FROM user_app_activity WHERE date = $1`,
            [targetDate]
        ).catch(() => ({ rows: [] }));
        const activityMap = {};
        appActivityRes.rows.forEach(r => {
            activityMap[r.user_id] = parseInt(r.active_seconds, 10);
        });

        // Fetch sessions conducted on target date from 'sessions' table
        const sessionsRes = await db.query(
            `SELECT practitioner_id, COUNT(*) as count 
             FROM sessions 
             WHERE DATE(start_time) = $1
             GROUP BY practitioner_id`,
            [targetDate]
        ).catch(() => ({ rows: [] }));
        const sessionsMap = {};
        sessionsRes.rows.forEach(r => { 
            if (r.practitioner_id) sessionsMap[r.practitioner_id] = parseInt(r.count, 10); 
        });

        // Fetch performance assessments created on target date
        const assessmentsRes = await db.query(
            `SELECT created_by, COUNT(*) as count
             FROM performance_assessments
             WHERE DATE(created_at) = $1 AND created_by IS NOT NULL
             GROUP BY created_by`,
            [targetDate]
        ).catch(() => ({ rows: [] }));
        const assessmentsMap = {};
        assessmentsRes.rows.forEach(r => { 
            if (r.created_by) assessmentsMap[r.created_by] = parseInt(r.count, 10); 
        });

        // Fetch user registrations created on target date
        const regRes = await db.query(
            `SELECT created_by, COUNT(*) as count
             FROM profiles
             WHERE DATE(created_at) = $1 AND created_by IS NOT NULL
             GROUP BY created_by`,
            [targetDate]
        ).catch(() => ({ rows: [] }));
        const regMap = {};
        regRes.rows.forEach(r => { 
            if (r.created_by) regMap[r.created_by] = parseInt(r.count, 10); 
        });

        // Build staff activity metrics
        const results = staffList.map(staff => {
            const activeSeconds = activityMap[staff.id] || 0;
            const activeMinutes = Math.round(activeSeconds / 60);

            const sessionsCount = (sessionsMap[staff.id] || 0) + (assessmentsMap[staff.id] || 0);
            const registrationsCount = regMap[staff.id] || 0;

            return {
                id: staff.id,
                name: `${staff.first_name || ''} ${staff.last_name || ''}`.trim() || staff.email,
                email: staff.email,
                role: staff.role,
                profession: staff.profession || staff.role,
                activeMinutes,
                sessionsCount,
                registrationsCount
            };
        });

        res.json({ date: targetDate, data: results });
    } catch (error) {
        console.error('Error in GET /staff-efficiency:', error);
        res.status(500).json({ error: error.message });
    }
};

router.get('/staff-efficiency', requireAuth, getActivityMetricsHandler);
router.get('/activity-tracker', requireAuth, getActivityMetricsHandler);

// GET Automation Settings
router.get('/activity-tracker/automation', requireAuth, async (req, res) => {
  try {
    const orgId = req.user.organization_id;
    const resDb = await db.query(
      `SELECT * FROM activity_tracker_automation WHERE organization_id = $1 OR organization_id IS NULL ORDER BY created_at DESC LIMIT 1`,
      [orgId]
    );
    const config = resDb.rows[0] || {
      is_enabled: false,
      recipient_emails: '',
      scheduled_time: '18:00',
      last_sent_date: null
    };
    res.json(config);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// POST Save Automation Settings
router.post('/activity-tracker/automation', requireAuth, async (req, res) => {
  try {
    const orgId = req.user.organization_id;
    const { is_enabled, recipient_emails, scheduled_time } = req.body;

    const existing = await db.query(
      `SELECT id FROM activity_tracker_automation WHERE organization_id = $1`,
      [orgId]
    );

    if (existing.rows.length > 0) {
      await db.query(
        `UPDATE activity_tracker_automation 
         SET is_enabled = $1, recipient_emails = $2, scheduled_time = $3, updated_at = CURRENT_TIMESTAMP
         WHERE organization_id = $4`,
        [is_enabled, recipient_emails, scheduled_time || '18:00', orgId]
      );
    } else {
      await db.query(
        `INSERT INTO activity_tracker_automation (organization_id, is_enabled, recipient_emails, scheduled_time)
         VALUES ($1, $2, $3, $4)`,
        [orgId, is_enabled, recipient_emails, scheduled_time || '18:00']
      );
    }

    res.json({ message: 'Automation settings saved successfully.' });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

const sendEmailHelper = async ({ to, subject, html }) => {
  const isPlaceholder = !process.env.SMTP_PASS || 
                        process.env.SMTP_PASS === 'your_smtp_password' || 
                        (process.env.SMTP_USER && process.env.SMTP_USER.includes('example'));

  if (isPlaceholder) {
    console.log(`[SMTP DEV MODE BROADCAST] Simulated email broadcast to: ${to}`);
    console.log(`[SMTP DEV MODE BROADCAST] Subject: ${subject}`);
    return { simulated: true };
  }

  return await transporter.sendMail({
    from: process.env.SMTP_FROM || 'noreply@ishpo.com',
    to,
    subject,
    html
  });
};

// POST Trigger Instant Broadcast Email
router.post('/activity-tracker/send-now', requireAuth, async (req, res) => {
  try {
    const { recipient_emails, date } = req.body;
    const targetDate = date || new Date().toISOString().split('T')[0];

    if (!recipient_emails || !recipient_emails.trim()) {
      return res.status(400).json({ error: 'Recipient emails are required.' });
    }

    const staffQuery = `
      SELECT p.id, p.first_name, p.last_name, p.profession, u.role, u.email
      FROM profiles p
      JOIN users u ON p.id = u.id
      WHERE u.role NOT IN ('client', 'athlete')
      ORDER BY p.first_name ASC
    `;
    const staffRes = await db.query(staffQuery);
    const staffList = staffRes.rows;

    const appActivityRes = await db.query(`SELECT user_id, active_seconds FROM user_app_activity WHERE date = $1`, [targetDate]).catch(() => ({ rows: [] }));
    const activityMap = {};
    appActivityRes.rows.forEach(r => { activityMap[r.user_id] = parseInt(r.active_seconds, 10); });

    const sessionsRes = await db.query(`SELECT practitioner_id, COUNT(*) as count FROM sessions WHERE DATE(start_time) = $1 GROUP BY practitioner_id`, [targetDate]).catch(() => ({ rows: [] }));
    const sessionsMap = {};
    sessionsRes.rows.forEach(r => { if (r.practitioner_id) sessionsMap[r.practitioner_id] = parseInt(r.count, 10); });

    const regRes = await db.query(`SELECT created_by, COUNT(*) as count FROM profiles WHERE DATE(created_at) = $1 AND created_by IS NOT NULL GROUP BY created_by`, [targetDate]).catch(() => ({ rows: [] }));
    const regMap = {};
    regRes.rows.forEach(r => { if (r.created_by) regMap[r.created_by] = parseInt(r.count, 10); });

    const staffData = staffList.map(staff => ({
      name: `${staff.first_name || ''} ${staff.last_name || ''}`.trim() || staff.email,
      profession: staff.profession || staff.role,
      activeMinutes: Math.round((activityMap[staff.id] || 0) / 60),
      sessionsCount: sessionsMap[staff.id] || 0,
      registrationsCount: regMap[staff.id] || 0
    }));

    const htmlContent = generateActivityTrackerHTML(targetDate, staffData);
    const emailList = recipient_emails.split(',').map(e => e.trim()).filter(Boolean);

    await sendEmailHelper({
      to: emailList.join(', '),
      subject: `[CSSH] Activity Tracker Daily Report - ${targetDate}`,
      html: htmlContent
    });

    res.json({ message: `Report successfully emailed to ${emailList.join(', ')}.` });
  } catch (err) {
    console.error('Error in send-now:', err);
    res.status(500).json({ error: err.message });
  }
});

// Scheduler loop running every 60 seconds to process automated daily email broadcasts
setInterval(async () => {
  try {
    const now = new Date();
    const currentTimeStr = `${String(now.getHours()).padStart(2, '0')}:${String(now.getMinutes()).padStart(2, '0')}`;
    const todayStr = now.toISOString().split('T')[0];

    const activeAutomations = await db.query(
      `SELECT * FROM activity_tracker_automation 
       WHERE is_enabled = true AND scheduled_time = $1 AND (last_sent_date IS NULL OR last_sent_date < $2)`,
      [currentTimeStr, todayStr]
    ).catch(() => ({ rows: [] }));

    for (const auto of activeAutomations.rows) {
      if (!auto.recipient_emails) continue;

      const emailList = auto.recipient_emails.split(',').map(e => e.trim()).filter(Boolean);
      if (emailList.length === 0) continue;

      const staffRes = await db.query(`SELECT p.id, p.first_name, p.last_name, p.profession, u.role, u.email FROM profiles p JOIN users u ON p.id = u.id WHERE u.role NOT IN ('client', 'athlete') ORDER BY p.first_name ASC`);
      const appActivityRes = await db.query(`SELECT user_id, active_seconds FROM user_app_activity WHERE date = $1`, [todayStr]).catch(() => ({ rows: [] }));
      const activityMap = {};
      appActivityRes.rows.forEach(r => { activityMap[r.user_id] = parseInt(r.active_seconds, 10); });

      const sessionsRes = await db.query(`SELECT practitioner_id, COUNT(*) as count FROM sessions WHERE DATE(start_time) = $1 GROUP BY practitioner_id`, [todayStr]).catch(() => ({ rows: [] }));
      const sessionsMap = {};
      sessionsRes.rows.forEach(r => { if (r.practitioner_id) sessionsMap[r.practitioner_id] = parseInt(r.count, 10); });

      const regRes = await db.query(`SELECT created_by, COUNT(*) as count FROM profiles WHERE DATE(created_at) = $1 AND created_by IS NOT NULL GROUP BY created_by`, [todayStr]).catch(() => ({ rows: [] }));
      const regMap = {};
      regRes.rows.forEach(r => { if (r.created_by) regMap[r.created_by] = parseInt(r.count, 10); });

      const staffData = staffRes.rows.map(staff => ({
        name: `${staff.first_name || ''} ${staff.last_name || ''}`.trim() || staff.email,
        profession: staff.profession || staff.role,
        activeMinutes: Math.round((activityMap[staff.id] || 0) / 60),
        sessionsCount: sessionsMap[staff.id] || 0,
        registrationsCount: regMap[staff.id] || 0
      }));

      const htmlContent = generateActivityTrackerHTML(todayStr, staffData);

      await sendEmailHelper({
        to: emailList.join(', '),
        subject: `[CSSH] Daily Activity Tracker Report - ${todayStr}`,
        html: htmlContent
      });

      await db.query(`UPDATE activity_tracker_automation SET last_sent_date = $1 WHERE id = $2`, [todayStr, auto.id]);
      console.log(`[AUTOMATION] Sent daily Activity Tracker email to ${emailList.join(', ')} for date ${todayStr}`);
    }
  } catch (err) {
    console.error('[AUTOMATION SCHEDULER ERROR]', err.message);
  }
}, 60000);

// GET all employees/staff for an organization
router.get('/employees', requireAuth, async (req, res) => {
    try {
        const orgId = req.user.organization_id;
        const { role_type } = req.query;

        let query = `
            SELECT p.*, u.email, u.role,
                   (SELECT json_agg(ca.*) FROM consultantavailability ca WHERE ca.consultant_id = p.id) as consultant_availability,
                   (SELECT json_agg(ea.*) FROM emergency_alerts ea WHERE ea.staff_id = p.id AND ea.status = 'unresolved') as emergency_alerts
            FROM profiles p
            JOIN users u ON p.id = u.id
            WHERE p.organization_id = $1 AND p.is_approved = true
        `;
        const params = [orgId];

        if (role_type === 'clinical') {
            query += ` AND (u.role IN ('consultant', 'sports_physician', 'physiotherapist', 'nutritionist', 'sports_scientist', 'massage_therapist') OR (u.role = 'admin' AND p.profession IS NOT NULL))`;
        } else if (role_type === 'athlete') {
            query += ` AND (u.role = 'athlete' OR p.ams_role = 'athlete')`;
        }

        const result = await db.query(query, params);
        res.json(result.rows);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

// GET employee directory for HR management
router.get('/employees/directory', requireAuth, async (req, res) => {
    try {
        const orgId = req.user.organization_id;
        const result = await db.query(`
            SELECT e.*, 
                   json_build_object('first_name', p.first_name, 'last_name', p.last_name, 'profession', p.profession) as profiles,
                   json_build_object('name', j.name) as jobs
            FROM hr_employees e
            LEFT JOIN profiles p ON e.profile_id = p.id
            LEFT JOIN hr_jobs j ON e.job_id = j.id
            WHERE e.organization_id = $1
        `, [orgId]);
        res.json({ data: result.rows });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

// GET today's attendance status for user
router.get('/attendance/today', requireAuth, async (req, res) => {
    try {
        const userId = req.user.id;
        const orgId = req.user.organization_id;
        if (orgId) {
            await runAutoCheckout(orgId);
        }
        const today = new Date().toISOString().split('T')[0];
        
        const result = await db.query(`
            SELECT * FROM hrattendancelogs 
            WHERE profile_id = $1 
            AND created_at >= $2::timestamp
            ORDER BY created_at DESC
            LIMIT 50
        `, [userId, today]);
        
        res.json({ data: result.rows });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

// GET all attendance logs for organization
router.get('/attendance/all', requireAuth, async (req, res) => {
    try {
        const orgId = req.user.organization_id;
        if (orgId) {
            await runAutoCheckout(orgId);
        }
        const result = await db.query(`
            SELECT a.*, 
                   json_build_object(
                       'first_name', p.first_name, 
                       'last_name', p.last_name, 
                       'profession', p.profession,
                       'email', u.email
                   ) as profile
            FROM hrattendancelogs a
            JOIN profiles p ON a.profile_id = p.id
            JOIN users u ON p.id = u.id
            WHERE a.organization_id = $1
            ORDER BY a.created_at DESC
        `, [orgId]);
        res.json({ data: result.rows });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

// GET filtered attendance logs for current user
router.get('/attendance/history', requireAuth, async (req, res) => {
    try {
        const userId = req.user.id;
        const { from, to } = req.query;
        
        let query = 'SELECT * FROM hrattendancelogs WHERE profile_id = $1';
        const params = [userId];
        
        if (from) {
            query += ` AND created_at >= $${params.length + 1}`;
            params.push(from);
        }
        if (to) {
            query += ` AND created_at <= $${params.length + 1}`;
            params.push(to);
        }
        
        query += ' ORDER BY created_at DESC';
        
        const result = await db.query(query, params);
        res.json(result.rows);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

// POST log attendance
router.post('/attendance/log', requireAuth, async (req, res) => {
    try {
        const userId = req.user.id;
        const orgId = req.user.organization_id;
        const { type, latitude, longitude, distance, metadata } = req.body;
        
        const result = await db.query(`
            INSERT INTO hrattendancelogs (
                organization_id, profile_id, type, latitude, longitude, distance_from_center, is_within_geofence, metadata
            ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
            RETURNING *
        `, [orgId, userId, type, latitude, longitude, distance, true, JSON.stringify(metadata || {})]);
        
        res.json({ data: result.rows[0] });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

// GET all users in organization (for approval/management)
// GET HR Stats
router.get('/stats', requireAuth, async (req, res) => {
    try {
        const orgId = req.user.organization_id;
        
        const [empCount, pendingLeaves, approvalCount] = await Promise.all([
            db.query('SELECT COUNT(*) FROM profiles WHERE organization_id = $1', [orgId]),
            db.query('SELECT COUNT(*) FROM hrleaves WHERE organization_id = $1 AND status = \'Requested\'', [orgId]),
            db.query('SELECT COUNT(*) FROM profiles WHERE organization_id = $1 AND is_approved = false', [orgId])
        ]);

        res.json({
            data: {
                totalEmployees: parseInt(empCount.rows[0].count),
                pendingLeaves: parseInt(pendingLeaves.rows[0].count),
                pendingApprovals: parseInt(approvalCount.rows[0].count)
            }
        });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

router.get('/users', requireAuth, async (req, res) => {
    try {
        const orgId = req.user.organization_id;
        
        const result = await db.query(`
            SELECT p.*, u.email, u.role as current_role
            FROM profiles p
            JOIN users u ON p.id = u.id
            WHERE p.organization_id = $1
            AND u.role != 'super_admin'
            ORDER BY u.created_at DESC
        `, [orgId]);
        
        res.json({ data: result.rows });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

// GET user profile details & active application time analytics
router.get('/users/:id/profile-activity', requireAuth, async (req, res) => {
    try {
        const { id } = req.params;
        const orgId = req.user.organization_id;

        // 1. User & Profile Details
        const userRes = await db.query(`
            SELECT p.*, u.email, u.role as current_role, u.created_at as user_created_at
            FROM profiles p
            JOIN users u ON p.id = u.id
            WHERE p.id = $1 AND (p.id = $4 OR p.organization_id = $2 OR $2 IS NULL OR $3 = 'super_admin')
        `, [id, orgId, req.user.role, req.user.id]).catch(() => ({ rows: [] }));

        if (!userRes.rows || userRes.rows.length === 0) {
            return res.status(404).json({ error: 'User profile not found' });
        }
        const profileData = userRes.rows[0];

        // 2. Today's Active Seconds
        let todaySeconds = 0;
        let lastPing = null;
        try {
            const todayRes = await db.query(`
                SELECT COALESCE(active_seconds, 0) as today_seconds, last_ping
                FROM user_app_activity
                WHERE user_id = $1 AND date = CURRENT_DATE
            `, [id]);
            todaySeconds = parseInt(todayRes.rows[0]?.today_seconds || 0, 10);
            lastPing = todayRes.rows[0]?.last_ping || null;
        } catch (e) {}

        // 3. Last 7 Days Active Seconds & Active Days
        let total7dSeconds = 0;
        let activeDays7d = 0;
        try {
            const last7dRes = await db.query(`
                SELECT 
                    COALESCE(SUM(active_seconds), 0) as total_7d_seconds,
                    COUNT(DISTINCT date) FILTER (WHERE active_seconds > 0) as active_days_7d
                FROM user_app_activity
                WHERE user_id = $1 AND date >= CURRENT_DATE - INTERVAL '6 days' AND date <= CURRENT_DATE
            `, [id]);
            total7dSeconds = parseInt(last7dRes.rows[0]?.total_7d_seconds || 0, 10);
            activeDays7d = parseInt(last7dRes.rows[0]?.active_days_7d || 0, 10);
        } catch (e) {}

        // 4. Last 30 Days Active Seconds & Active Days
        let total30dSeconds = 0;
        let activeDays30d = 0;
        try {
            const last30dRes = await db.query(`
                SELECT 
                    COALESCE(SUM(active_seconds), 0) as total_30d_seconds,
                    COUNT(DISTINCT date) FILTER (WHERE active_seconds > 0) as active_days_30d
                FROM user_app_activity
                WHERE user_id = $1 AND date >= CURRENT_DATE - INTERVAL '29 days' AND date <= CURRENT_DATE
            `, [id]);
            total30dSeconds = parseInt(last30dRes.rows[0]?.total_30d_seconds || 0, 10);
            activeDays30d = parseInt(last30dRes.rows[0]?.active_days_30d || 0, 10);
        } catch (e) {}

        // 5. Daily Activity Trend for Last 14 Days
        let dailyTrend = [];
        try {
            const trendRes = await db.query(`
                SELECT d.date::text as date_str, COALESCE(a.active_seconds, 0) as active_seconds
                FROM generate_series(CURRENT_DATE - INTERVAL '13 days', CURRENT_DATE, '1 day'::interval) d(date)
                LEFT JOIN user_app_activity a ON a.user_id = $1 AND a.date = d.date::date
                ORDER BY d.date ASC
            `, [id]);
            dailyTrend = trendRes.rows.map(r => ({
                date: r.date_str,
                activeMinutes: Math.round(parseInt(r.active_seconds || 0, 10) / 60)
            }));
        } catch (e) {}

        // 6. Productivity Summary Counts
        let sessionsCount = 0;
        let assessmentsCount = 0;
        let registrationsCount = 0;
        try {
            const sessionsRes = await db.query(`SELECT COUNT(*) as count FROM sessions WHERE practitioner_id = $1`, [id]).catch(() => ({ rows: [{ count: 0 }] }));
            sessionsCount = parseInt(sessionsRes.rows[0]?.count || 0, 10);
        } catch (e) {}

        const todayMinutes = Math.round(todaySeconds / 60);
        const avg7dMinutes = Math.round((total7dSeconds / 7) / 60);
        const avg30dMinutes = Math.round((total30dSeconds / 30) / 60);

        res.json({
            profile: profileData,
            activeTime: {
                todaySeconds,
                todayMinutes,
                lastPing,
                total7dSeconds,
                avg7dMinutes,
                activeDays7d,
                total30dSeconds,
                avg30dMinutes,
                activeDays30d,
                dailyTrend
            },
            productivity: {
                sessionsCount,
                assessmentsCount,
                registrationsCount
            }
        });
    } catch (error) {
        console.error('Error fetching user profile activity:', error);
        res.status(500).json({ error: error.message });
    }
});

// POST approve user
router.post('/users/:id/approve', requireAuth, async (req, res) => {
    const client = await db.connect();
    try {
        const { id } = req.params;
        const { role, profession, ams_role, uhid } = req.body;
        const orgId = req.user.organization_id;

        await client.query('BEGIN');

        let finalUhid = uhid || null;
        if ((role === 'client' || role === 'athlete') && !finalUhid) {
            const uhidRes = await client.query('SELECT generate_uhid_func($1) as new_uhid', [orgId]);
            finalUhid = uhidRes.rows[0].new_uhid;
        }

        // 1. Update Profile
        await client.query(`
            UPDATE profiles SET 
                is_approved = true,
                profession = $1,
                ams_role = $2,
                uhid = $3
            WHERE id = $4 AND organization_id = $5
        `, [profession || null, ams_role || null, finalUhid, id, orgId]);

        // 2. Update User Role
        await client.query('UPDATE users SET role = $1 WHERE id = $2', [role, id]);

        // --- Auto-allocation trigger ---
        if (profession) {
            await autoAllocateStaffServices(id, profession, orgId, client);
        }

        await client.query('COMMIT');

        // Notify the approved user directly
        const approvedUserName = `${profession ? profession.replace(/_/g, ' ') : (role || 'user')}`;
        await db.query(`
            INSERT INTO notifications (
                organization_id, title, content, type, target_user_id, category
            ) VALUES ($1, $2, $3, $4, $5, $6)
        `, [
            orgId,
            'Account Approved',
            `Your account has been approved. You have been assigned the role of ${role}${profession ? ` (${profession})` : ''}. You can now log in and access the system.`,
            'green',
            id,
            'in_app'
        ]);

        res.json({ success: true });
    } catch (error) {
        await client.query('ROLLBACK');
        res.status(500).json({ error: error.message });
    } finally {
        client.release();
    }
});

// PATCH update user role
router.patch('/users/:id/role', requireAuth, async (req, res) => {
    const client = await db.connect();
    try {
        const { id } = req.params;
        const { role, profession, ams_role, uhid, has_calendar_access, has_analytics_access, has_assign_work_access, allowed_consoles } = req.body;
        const orgId = req.user.organization_id;

        // Security check for calendar access, analytics access, or assign work access change
        if ((has_calendar_access !== undefined || has_analytics_access !== undefined || has_assign_work_access !== undefined || allowed_consoles !== undefined) && req.user.role !== 'admin') {
            return res.status(403).json({ error: 'Forbidden: Only administrators can modify access permissions' });
        }

        await client.query('BEGIN');

        if (role) {
            await client.query('UPDATE Users SET role = $1 WHERE id = $2', [role, id]);
        }

        const updates = [];
        const params = [id, orgId];
        if (profession !== undefined) {
            updates.push(`profession = $${params.length + 1}`);
            params.push(profession);
        }
        if (ams_role !== undefined) {
            updates.push(`ams_role = $${params.length + 1}`);
            params.push(ams_role);
        }
        if (uhid !== undefined) {
            updates.push(`uhid = $${params.length + 1}`);
            params.push(uhid);
        }
        if (has_calendar_access !== undefined) {
            updates.push(`has_calendar_access = $${params.length + 1}`);
            params.push(has_calendar_access);
        }
        if (has_analytics_access !== undefined) {
            updates.push(`has_analytics_access = $${params.length + 1}`);
            params.push(has_analytics_access);
        }
        if (has_assign_work_access !== undefined) {
            updates.push(`has_assign_work_access = $${params.length + 1}`);
            params.push(has_assign_work_access);
        }
        if (allowed_consoles !== undefined) {
            updates.push(`allowed_consoles = $${params.length + 1}`);
            params.push(typeof allowed_consoles === 'object' ? JSON.stringify(allowed_consoles) : allowed_consoles);
        }

        if (updates.length > 0) {
            await client.query(`
                UPDATE profiles SET ${updates.join(', ')}
                WHERE id = $1 AND organization_id = $2
            `, params);
        }

        // --- Auto-allocation trigger ---
        if (profession) {
            await autoAllocateStaffServices(id, profession, orgId, client);
        }

        await client.query('COMMIT');

        // Notify the affected user about their role/profession/permissions change
        const changeDetails = [];
        if (role) changeDetails.push(`Role: ${role}`);
        if (profession !== undefined) changeDetails.push(`Profession: ${profession || 'N/A'}`);
        if (ams_role !== undefined) changeDetails.push(`AMS Role: ${ams_role || 'N/A'}`);
        if (has_calendar_access !== undefined) changeDetails.push(`Calendar Access: ${has_calendar_access ? 'Enabled' : 'Disabled'}`);
        if (has_analytics_access !== undefined) changeDetails.push(`Analytics Access: ${has_analytics_access ? 'Enabled' : 'Disabled'}`);
        if (has_assign_work_access !== undefined) changeDetails.push(`Work Assignment: ${has_assign_work_access ? 'Enabled' : 'Disabled'}`);
        if (allowed_consoles !== undefined) changeDetails.push(`Console Access Permissions Updated`);

        if (changeDetails.length > 0) {
            await db.query(`
                INSERT INTO notifications (
                    organization_id, title, content, type, target_user_id, category
                ) VALUES ($1, $2, $3, $4, $5, $6)
            `, [
                orgId,
                'Your Role Has Been Updated',
                `An administrator has updated your profile. Changes: ${changeDetails.join(', ')}.`,
                'blue',
                id,
                'in_app'
            ]);
        }

        res.json({ success: true });
    } catch (error) {
        await client.query('ROLLBACK');
        res.status(500).json({ error: error.message });
    } finally {
        client.release();
    }
});

// DELETE permanently delete user
router.delete('/users/:id', requireAuth, async (req, res) => {
    try {
        const { id } = req.params;
        const orgId = req.user.organization_id;

        // Verify organization match before deleting
        const profileRes = await db.query('SELECT organization_id FROM profiles WHERE id = $1', [id]);
        if (profileRes.rows.length === 0 || profileRes.rows[0].organization_id !== orgId) {
            return res.status(403).json({ error: 'Unauthorized user deletion' });
        }

        // Permanently delete user (cascades to profiles)
        await db.query('DELETE FROM users WHERE id = $1', [id]);

        res.json({ success: true });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

// POST create user (direct)
router.post('/users', requireAuth, async (req, res) => {
    const client = await db.connect();
    try {
        const { email, firstName, lastName, role, profession, uhid, ams_role } = req.body;
        const orgId = req.user.organization_id;
        
        // Generate random password
        const password = Math.random().toString(36).slice(-8);
        const bcrypt = await import('bcrypt');
        const passwordHash = await bcrypt.default.hash(password, 10);
        const userId = (await import('crypto')).randomUUID();

        await client.query('BEGIN');

        // 1. Insert User
        await client.query(
            'INSERT INTO users (id, email, password_hash, role) VALUES ($1, $2, $3, $4)',
            [userId, email, passwordHash, role]
        );

        // 2. Insert Profile
        await client.query(
            'INSERT INTO profiles (id, first_name, last_name, organization_id, is_approved, profession, uhid, ams_role) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)',
            [userId, firstName, lastName, orgId, true, profession || null, uhid || null, ams_role || null]
        );

        // --- Auto-allocation trigger ---
        if (profession) {
            await autoAllocateStaffServices(userId, profession, orgId, client);
        }

        await client.query('COMMIT');
        res.json({ success: true, user: { email, password } });
    } catch (error) {
        await client.query('ROLLBACK');
        res.status(500).json({ error: error.message });
    } finally {
        client.release();
    }
});

// GET all leave requests for organization
router.get('/leaves', requireAuth, async (req, res) => {
    try {
        const orgId = req.user.organization_id;
        const { employee_id, status } = req.query;

        let query = `
            SELECT l.*, p.first_name, p.last_name
            FROM hrleaves l
            JOIN profiles p ON l.employee_id = p.id
            WHERE l.organization_id = $1
        `;
        const params = [orgId];

        if (employee_id) {
            query += ` AND l.employee_id = $${params.length + 1}`;
            params.push(employee_id);
        }
        if (status) {
            query += ` AND l.status = $${params.length + 1}`;
            params.push(status);
        }

        query += ' ORDER BY l.created_at DESC';

        const result = await db.query(query, params);
        res.json({ data: result.rows });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

// POST new leave request
router.post('/leaves', requireAuth, async (req, res) => {
    try {
        const userId = req.user.id;
        const orgId = req.user.organization_id;
        const { leave_type, start_date, end_date, reason } = req.body;

        const normalizedType = (leave_type || '').toLowerCase();
        const isImmediateAllowed = normalizedType.includes('sick') || normalizedType.includes('emergency') || normalizedType.includes('medical');

        const today = new Date();
        today.setHours(0, 0, 0, 0);

        const startDateObj = new Date(start_date);
        startDateObj.setHours(0, 0, 0, 0);

        if (!isImmediateAllowed) {
            const minAllowed = new Date(today);
            minAllowed.setDate(minAllowed.getDate() + 2); // 48 hours / 2 days prior notice required
            if (startDateObj < minAllowed) {
                return res.status(400).json({
                    error: 'Casual and regular leaves must be applied at least 48 hours in advance (today and tomorrow are disallowed).'
                });
            }
        } else {
            if (startDateObj < today) {
                return res.status(400).json({ error: 'Cannot apply leave for past dates.' });
            }
        }

        const result = await db.query(`
            INSERT INTO hrleaves (
                organization_id, employee_id, leave_type, start_date, end_date, reason
            ) VALUES ($1, $2, $3, $4, $5, $6)
            RETURNING *
        `, [orgId, userId, leave_type, start_date, end_date, reason]);

        // Notify hr_manager about the new leave request
        const staffRes = await db.query('SELECT first_name, last_name FROM profiles WHERE id = $1', [userId]);
        const staffName = staffRes.rows.length > 0 ? `${staffRes.rows[0].first_name} ${staffRes.rows[0].last_name}` : 'A staff member';
        const leaveFrom = new Date(start_date).toLocaleDateString('en-IN', { dateStyle: 'medium' });
        const leaveTo = new Date(end_date).toLocaleDateString('en-IN', { dateStyle: 'medium' });

        await db.query(`
            INSERT INTO notifications (organization_id, title, content, type, target_role, category)
            VALUES ($1, $2, $3, $4, $5, $6)
        `, [
            orgId,
            'Leave Request Submitted',
            `${staffName} has submitted a ${leave_type} leave request from ${leaveFrom} to ${leaveTo}.`,
            'amber',
            'hr_manager',
            'in_app'
        ]);

        res.status(201).json({ data: result.rows[0] });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});


// PATCH update leave status
router.patch('/leaves/:id', requireAuth, async (req, res) => {
    try {
        const { id } = req.params;
        const { status } = req.body;
        const orgId = req.user.organization_id;
        const userId = req.user.id;

        const result = await db.query(`
            UPDATE hrleaves SET 
                status = $1,
                approved_by = $2
            WHERE id = $3 AND organization_id = $4
            RETURNING *
        `, [status, userId, id, orgId]);

        const leave = result.rows[0];

        // Notify the employee about their leave status outcome
        const normalizedStatus = (status || '').toLowerCase();
        if (leave && leave.employee_id && (normalizedStatus === 'approved' || normalizedStatus === 'rejected')) {
            const statusLabel = normalizedStatus.charAt(0).toUpperCase() + normalizedStatus.slice(1);
            const leaveFrom = new Date(leave.start_date).toLocaleDateString('en-IN', { dateStyle: 'medium' });
            const leaveTo = new Date(leave.end_date).toLocaleDateString('en-IN', { dateStyle: 'medium' });
            await db.query(`
                INSERT INTO notifications (organization_id, title, content, type, target_user_id, category)
                VALUES ($1, $2, $3, $4, $5, $6)
            `, [
                orgId,
                `Leave Request ${statusLabel}`,
                `Your ${leave.leave_type} leave request from ${leaveFrom} to ${leaveTo} has been ${normalizedStatus}.`,
                normalizedStatus === 'approved' ? 'green' : 'red',
                leave.employee_id,
                'in_app'
            ]);
        }

        res.json({ data: leave });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

// GET leave balances & used leave counts
router.get('/leave-balances', requireAuth, async (req, res) => {
    try {
        const orgId = req.user.organization_id;
        const targetUserId = req.query.employee_id || req.user.id;
        const fetchAll = req.query.all === 'true' || req.query.all === '1';

        if (fetchAll) {
            // Return all employees leave balances in org
            const employeesRes = await db.query(`
                SELECT p.id as employee_id, p.first_name, p.last_name, p.profession, u.email,
                       COALESCE(b.casual_leave, 12) as casual_leave,
                       COALESCE(b.sick_leave, 4) as sick_leave,
                       COALESCE(b.paid_leave, 0) as paid_leave,
                       COALESCE(b.emergency_leave, 0) as emergency_leave
                FROM profiles p
                JOIN users u ON p.id = u.id
                LEFT JOIN hr_leave_balances b ON p.id = b.employee_id AND b.organization_id = $1
                WHERE p.organization_id = $1
                ORDER BY p.first_name ASC
            `, [orgId]);

            const leavesRes = await db.query(`
                SELECT employee_id, leave_type, start_date, end_date, status
                FROM hrleaves
                WHERE organization_id = $1 AND status = 'Approved'
            `, [orgId]);

            const result = employeesRes.rows.map(emp => {
                const empLeaves = leavesRes.rows.filter(l => l.employee_id === emp.employee_id);
                
                let usedCasual = 0, usedSick = 0, usedPaid = 0, usedEmergency = 0, lopDays = 0;
                empLeaves.forEach(l => {
                    const days = Math.max(1, Math.ceil((new Date(l.end_date) - new Date(l.start_date)) / (1000 * 60 * 60 * 24)) + 1);
                    const type = (l.leave_type || '').toLowerCase();
                    if (type.includes('casual')) usedCasual += days;
                    else if (type.includes('sick') || type.includes('medical')) usedSick += days;
                    else if (type.includes('annual') || type.includes('paid')) usedPaid += days;
                    else if (type.includes('emergency')) usedEmergency += days;
                    else lopDays += days;
                });

                // Calculate LOP for exceed balance
                if (usedCasual > emp.casual_leave) lopDays += (usedCasual - emp.casual_leave);
                if (usedSick > emp.sick_leave) lopDays += (usedSick - emp.sick_leave);
                if (usedPaid > emp.paid_leave) lopDays += (usedPaid - emp.paid_leave);
                if (usedEmergency > emp.emergency_leave) lopDays += (usedEmergency - emp.emergency_leave);

                return {
                    ...emp,
                    used: {
                        casual: usedCasual,
                        sick: usedSick,
                        paid: usedPaid,
                        emergency: usedEmergency,
                        lop: lopDays
                    },
                    available: {
                        casual: Math.max(0, emp.casual_leave - usedCasual),
                        sick: Math.max(0, emp.sick_leave - usedSick),
                        paid: Math.max(0, emp.paid_leave - usedPaid),
                        emergency: Math.max(0, emp.emergency_leave - usedEmergency)
                    }
                };
            });

            return res.json({ data: result });
        }

        // Return single employee leave balance
        const balanceRes = await db.query(`
            SELECT casual_leave, sick_leave, paid_leave, emergency_leave
            FROM hr_leave_balances
            WHERE organization_id = $1 AND employee_id = $2
        `, [orgId, targetUserId]);

        const quota = balanceRes.rows[0] || { casual_leave: 12, sick_leave: 4, paid_leave: 0, emergency_leave: 0 };

        const leavesRes = await db.query(`
            SELECT leave_type, start_date, end_date, status
            FROM hrleaves
            WHERE organization_id = $1 AND employee_id = $2 AND status = 'Approved'
        `, [orgId, targetUserId]);

        let usedCasual = 0, usedSick = 0, usedPaid = 0, usedEmergency = 0, lopDays = 0;
        leavesRes.rows.forEach(l => {
            const days = Math.max(1, Math.ceil((new Date(l.end_date) - new Date(l.start_date)) / (1000 * 60 * 60 * 24)) + 1);
            const type = (l.leave_type || '').toLowerCase();
            if (type.includes('casual')) usedCasual += days;
            else if (type.includes('sick') || type.includes('medical')) usedSick += days;
            else if (type.includes('annual') || type.includes('paid')) usedPaid += days;
            else if (type.includes('emergency')) usedEmergency += days;
            else lopDays += days;
        });

        if (usedCasual > quota.casual_leave) lopDays += (usedCasual - quota.casual_leave);
        if (usedSick > quota.sick_leave) lopDays += (usedSick - quota.sick_leave);
        if (usedPaid > quota.paid_leave) lopDays += (usedPaid - quota.paid_leave);
        if (usedEmergency > quota.emergency_leave) lopDays += (usedEmergency - quota.emergency_leave);

        return res.json({
            data: {
                employee_id: targetUserId,
                quota,
                used: {
                    casual: usedCasual,
                    sick: usedSick,
                    paid: usedPaid,
                    emergency: usedEmergency,
                    lop: lopDays
                },
                available: {
                    casual: Math.max(0, quota.casual_leave - usedCasual),
                    sick: Math.max(0, quota.sick_leave - usedSick),
                    paid: Math.max(0, quota.paid_leave - usedPaid),
                    emergency: Math.max(0, quota.emergency_leave - usedEmergency)
                }
            }
        });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

// PUT / POST update leave quota for an employee (HR only)
router.put('/leave-balances/:employee_id', requireAuth, async (req, res) => {
    try {
        const orgId = req.user.organization_id;
        const { employee_id } = req.params;
        const { casual_leave, sick_leave, paid_leave, emergency_leave } = req.body;

        const result = await db.query(`
            INSERT INTO hr_leave_balances (
                organization_id, employee_id, casual_leave, sick_leave, paid_leave, emergency_leave, updated_at
            ) VALUES ($1, $2, $3, $4, $5, $6, CURRENT_TIMESTAMP)
            ON CONFLICT (organization_id, employee_id)
            DO UPDATE SET
                casual_leave = EXCLUDED.casual_leave,
                sick_leave = EXCLUDED.sick_leave,
                paid_leave = EXCLUDED.paid_leave,
                emergency_leave = EXCLUDED.emergency_leave,
                updated_at = CURRENT_TIMESTAMP
            RETURNING *
        `, [
            orgId,
            employee_id,
            casual_leave !== undefined ? parseInt(casual_leave) : 12,
            sick_leave !== undefined ? parseInt(sick_leave) : 4,
            paid_leave !== undefined ? parseInt(paid_leave) : 0,
            emergency_leave !== undefined ? parseInt(emergency_leave) : 0
        ]);

        res.json({ data: result.rows[0] });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});


// GET emergency alerts
router.get('/emergencies', requireAuth, async (req, res) => {
    try {
        const orgId = req.user.organization_id;
        const { staff_id, status } = req.query;

        let query = `
            SELECT e.*, 
                   json_build_object('id', p.id, 'first_name', p.first_name, 'last_name', p.last_name, 'profession', p.profession) as staff
            FROM emergency_alerts e
            JOIN profiles p ON e.staff_id = p.id
            WHERE e.organization_id = $1
        `;
        const params = [orgId];

        if (staff_id) {
            query += ` AND e.staff_id = $${params.length + 1}`;
            params.push(staff_id);
        }
        if (status) {
            query += ` AND e.status = $${params.length + 1}`;
            params.push(status);
        }

        query += ' ORDER BY e.created_at DESC';

        const result = await db.query(query, params);
        res.json({ data: result.rows });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

// GET latest emergency alert for staff today
router.get('/emergency-alerts/today', requireAuth, async (req, res) => {
    try {
        const staffId = req.user.id;
        const today = new Date().toISOString().split('T')[0];

        const result = await db.query(`
            SELECT * FROM emergency_alerts 
            WHERE staff_id = $1 AND created_at >= $2
            ORDER BY created_at DESC LIMIT 1
        `, [staffId, `${today} 00:00:00`]);

        res.json(result.rows);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

// POST emergency alert (and auto checkout)
router.post('/emergency-alerts', requireAuth, async (req, res) => {
    const client = await db.connect();
    try {
        const { reason } = req.body;
        const staffId = req.user.id;
        const orgId = req.user.organization_id;

        await client.query('BEGIN');

        // 1. Insert alert
        const alertRes = await client.query(`
            INSERT INTO emergency_alerts (organization_id, staff_id, reason, status)
            VALUES ($1, $2, $3, $4) RETURNING *
        `, [orgId, staffId, reason, 'unresolved']);

        const staffRes = await client.query('SELECT first_name, last_name FROM profiles WHERE id = $1', [staffId]);
        const staffName = staffRes.rows.length > 0 ? `${staffRes.rows[0].first_name} ${staffRes.rows[0].last_name}` : 'A staff member';

        const settingsRes = await client.query(
            'SELECT enable_in_app_notifications, notify_emergency_leave FROM organization_notification_settings WHERE organization_id = $1',
            [orgId]
        );
        const shouldNotify = settingsRes.rows.length > 0
            ? (settingsRes.rows[0].enable_in_app_notifications && settingsRes.rows[0].notify_emergency_leave)
            : true;

        if (shouldNotify) {
            await client.query(`
                INSERT INTO notifications (
                    organization_id, title, content, type, target_role, category, action_payload, action_status, sender_id
                ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
            `, [
                orgId,
                'Emergency Leave Activated',
                `${staffName} has activated Emergency Leave.`,
                'red',
                'admin',
                'direct_action',
                JSON.stringify({ staffId, alertId: alertRes.rows[0].id }),
                'pending',
                staffId
            ]);
        }

        // 2. Handle auto checkout/leave
        const today = new Date().toISOString().split('T')[0];
        const logsRes = await client.query(`
            SELECT * FROM hrattendancelogs 
            WHERE profile_id = $1 AND created_at >= $2
            ORDER BY created_at DESC
        `, [staffId, `${today} 00:00:00`]);
        
        const logs = logsRes.rows;
        const lastCheckIn = logs.find(l => l.type === 'check_in');
        const alreadyCheckedOut = logs.some(l => l.type === 'check_out');

        if (lastCheckIn && !alreadyCheckedOut) {
            await client.query(`
                INSERT INTO hrattendancelogs (
                    organization_id, profile_id, type, latitude, longitude, 
                    distance_from_center, is_within_geofence, metadata
                ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
            `, [
                orgId, staffId, 'emergency_leave', lastCheckIn.latitude, lastCheckIn.longitude,
                lastCheckIn.distance_from_center, lastCheckIn.is_within_geofence,
                JSON.stringify({ auto: true, reason: 'emergency_leave', note: 'Auto-checked out due to emergency leave' })
            ]);
        } else if (!lastCheckIn) {
            await client.query(`
                INSERT INTO hrattendancelogs (
                    organization_id, profile_id, type, is_within_geofence, metadata
                ) VALUES ($1, $2, $3, $4, $5)
            `, [
                orgId, staffId, 'emergency_leave', false,
                JSON.stringify({ reason: 'emergency_leave', note: 'Emergency leave raised — no prior check-in for today' })
            ]);
        }

        await client.query('COMMIT');
        res.status(201).json(alertRes.rows[0]);
    } catch (error) {
        await client.query('ROLLBACK');
        res.status(500).json({ error: error.message });
    } finally {
        client.release();
    }
});

// PATCH resolve emergency alert
router.patch('/emergencies/:id', requireAuth, async (req, res) => {
    try {
        const { id } = req.params;
        const orgId = req.user.organization_id;
        const { status, admin_decision } = req.body;
        
        const result = await db.query(`
            UPDATE emergency_alerts 
            SET status = $1, admin_decision = $2, updated_at = NOW()
            WHERE id = $3 AND organization_id = $4
            RETURNING *
        `, [status, admin_decision, id, orgId]);
        
        if (result.rows.length === 0) return res.status(404).json({ error: 'Alert not found' });
        res.json(result.rows[0]);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

// GET unread notifications count
router.get('/notifications/unread-count', requireAuth, async (req, res) => {
    try {
        const userId = req.user.id;
        const orgId = req.user.organization_id;
        const userRole = req.user.role;
        
        const result = await db.query(`
            SELECT COUNT(*)::int as count
            FROM notifications n
            WHERE n.organization_id = $1
            AND (
                n.is_broadcast = true 
                OR n.target_user_id = $2 
                OR n.target_role = $3
                OR (n.target_role = 'admin' AND $3 = 'super_admin')
                OR (n.target_role = 'athlete' AND $3 IN ('athlete', 'client'))
                OR (n.target_role = 'specialist' AND $3 IN ('sports_scientist', 'sports_physician', 'physiotherapist', 'nutritionist', 'massage_therapist', 'coach'))
                OR (n.target_role IS NULL AND n.target_user_id IS NULL AND n.is_broadcast IS NOT TRUE AND ($3 = 'admin' OR $3 = 'super_admin'))
            )
            AND NOT EXISTS (
                SELECT 1 FROM notification_reads nr 
                WHERE nr.notification_id = n.id AND nr.user_id = $2
            )
        `, [orgId, userId, userRole]);
        
        res.json({ unreadCount: result.rows[0].count });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

// GET all staff schedules for organization
router.get('/staff-schedules', requireAuth, async (req, res) => {
    try {
        const orgId = req.user.organization_id;
        const result = await db.query(
            'SELECT * FROM staff_schedules WHERE organization_id = $1',
            [orgId]
        );
        res.json(result.rows);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

// GET individual schedule (fallback to default if none exists)
router.get('/staff-schedules/:consultant_id', requireAuth, async (req, res) => {
    try {
        const { consultant_id } = req.params;
        const orgId = req.user.organization_id;
        const result = await db.query(
            'SELECT * FROM staff_schedules WHERE consultant_id = $1 AND organization_id = $2',
            [consultant_id, orgId]
        );
        if (result.rows.length > 0) {
            res.json(result.rows[0]);
        } else {
            res.json({
                consultant_id,
                shift_start: '08:00:00',
                shift_end: '17:00:00',
                breaks: []
            });
        }
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

// POST upsert staff schedule
router.post('/staff-schedules', requireAuth, async (req, res) => {
    try {
        const { organization_id, consultant_id, shift_start, shift_end, breaks } = req.body;
        const orgId = organization_id || req.user.organization_id;

        if (!consultant_id) {
            return res.status(400).json({ error: 'consultant_id is required' });
        }

        let breaksJson;
        if (typeof breaks === 'string') {
            breaksJson = breaks;
        } else {
            breaksJson = JSON.stringify(breaks || []);
        }

        const query = `
            INSERT INTO staff_schedules (organization_id, consultant_id, shift_start, shift_end, breaks, updated_at)
            VALUES ($1, $2, $3, $4, $5, CURRENT_TIMESTAMP)
            ON CONFLICT (consultant_id)
            DO UPDATE SET
                organization_id = EXCLUDED.organization_id,
                shift_start = EXCLUDED.shift_start,
                shift_end = EXCLUDED.shift_end,
                breaks = EXCLUDED.breaks,
                updated_at = CURRENT_TIMESTAMP
            RETURNING *
        `;

        const result = await db.query(query, [
            orgId,
            consultant_id,
            shift_start || '08:00:00',
            shift_end || '17:00:00',
            breaksJson
        ]);

        res.json(result.rows[0]);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});


// ─────────────────────────────────────────────────────────────────────────────
// AUTO CLOCK-OUT LOGIC
// Runs on a 60-second interval. If the current time has passed an org's
// configured default_checkout_time and any staff member is still checked-in
// with no corresponding check_out for today, we insert an automatic check_out
// log with a descriptive remark.
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Track which (org_id, date) pairs have already been auto-checked-out today
 * so we never double-process the same day for the same org.
 */
/**
 * Core auto-checkout function.
 * Enforces auto clock-out after the org's default shift end time.
 * If a user clocks in and forgets to clock out, the system automatically
 * creates a check_out log at the default shift end time (default_checkout_time).
 *
 * @param {string|null} targetOrgId - Optional org ID to target.
 * @returns {Promise<{ processed: number }>}
 */
async function runAutoCheckout(targetOrgId = null) {
    try {
        let orgsResult;
        if (targetOrgId) {
            orgsResult = await db.query(
                `SELECT id, default_checkout_time, default_shift_end_time FROM organizations WHERE id = $1 AND status = 'active'`,
                [targetOrgId]
            );
        } else {
            orgsResult = await db.query(
                `SELECT id, default_checkout_time, default_shift_end_time FROM organizations WHERE status = 'active'`
            );
        }

        let totalProcessed = 0;
        const now = new Date();

        for (const org of orgsResult.rows) {
            const orgId = org.id;
            const timeVal = org.default_shift_end_time || org.default_checkout_time;
            let defaultCheckoutTimeStr = '18:00';
            if (timeVal) {
                if (typeof timeVal === 'string') {
                    defaultCheckoutTimeStr = timeVal.substring(0, 5);
                } else if (timeVal instanceof Date) {
                    defaultCheckoutTimeStr = timeVal.toTimeString().substring(0, 5);
                }
            }

            // Find all check_in logs for this org that have NO corresponding check_out log after them
            const stuckResult = await db.query(`
                SELECT a.id AS checkin_id,
                       a.profile_id,
                       a.latitude,
                       a.longitude,
                       a.distance_from_center,
                       a.created_at AS checkin_time
                FROM hrattendancelogs a
                WHERE a.organization_id = $1
                  AND a.type = 'check_in'
                  AND NOT EXISTS (
                      SELECT 1 FROM hrattendancelogs b
                      WHERE b.profile_id = a.profile_id
                        AND b.organization_id = a.organization_id
                        AND (b.type = 'check_out' OR b.type = 'emergency_leave')
                        AND b.created_at > a.created_at
                  )
                ORDER BY a.created_at ASC
            `, [orgId]);

            for (const row of stuckResult.rows) {
                const checkinDate = new Date(row.checkin_time);
                // Extract local date YYYY-MM-DD in Asia/Kolkata timezone
                const localDateStr = checkinDate.toLocaleDateString('en-CA', { timeZone: 'Asia/Kolkata' });

                // Construct ISO timestamp for shift end in IST (+05:30)
                const autoCheckoutIso = new Date(`${localDateStr}T${defaultCheckoutTimeStr}:00+05:30`).toISOString();
                const autoCheckoutDate = new Date(autoCheckoutIso);

                // If current time has passed the default shift end time for this check-in:
                if (now >= autoCheckoutDate) {
                    const remark = `Auto clock-out applied. Staff did not manually check out. Default shift end time (${defaultCheckoutTimeStr}) was enforced.`;
                    const autoMetadata = {
                        auto_checkout: true,
                        remark,
                        default_checkout_time: defaultCheckoutTimeStr,
                        original_checkin_time: row.checkin_time,
                    };

                    await db.query(`
                        INSERT INTO hrattendancelogs (
                            organization_id,
                            profile_id,
                            type,
                            latitude,
                            longitude,
                            distance_from_center,
                            is_within_geofence,
                            metadata,
                            remark,
                            created_at
                        ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10::timestamptz)
                    `, [
                        orgId,
                        row.profile_id,
                        'check_out',
                        row.latitude,
                        row.longitude,
                        row.distance_from_center,
                        true,
                        JSON.stringify(autoMetadata),
                        remark,
                        autoCheckoutIso
                    ]);

                    totalProcessed++;
                    console.log(`[AUTO-CHECKOUT] Org ${orgId} | User ${row.profile_id} auto-checked-out for date ${localDateStr} at ${defaultCheckoutTimeStr}`);
                }
            }
        }

        return { processed: totalProcessed };
    } catch (err) {
        console.error('[AUTO-CHECKOUT] Error:', err.message);
        return { processed: 0, error: err.message };
    }
}

// POST /attendance/auto-checkout — Manual trigger (admin/HR use)
router.post('/attendance/auto-checkout', requireAuth, async (req, res) => {
    try {
        const orgId = req.user.organization_id;
        const result = await runAutoCheckout(orgId);
        res.json({ success: true, ...result });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

// ── Scheduler — runs every 60 seconds ─────────────────────────────────────────
setInterval(async () => {
    await runAutoCheckout();
}, 60_000);

export default router;
