import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { supabase } from "@/integrations/supabase/client";

interface ExportData {
  clientName: string;
  uhid: string;
  questionnaireName: string;
  specialistName: string;
  respondedAt: string;
  answers: any[];
  interpretation: string;
  orgId: string;
}

export const exportQuestionnairePDF = async (data: ExportData) => {
  const { 
    clientName, 
    uhid, 
    questionnaireName, 
    specialistName, 
    respondedAt, 
    answers, 
    interpretation, 
    orgId 
  } = data;

  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // 1. Fetch Org Branding
  const { data: org } = await supabase
    .from("organizations")
    .select("official_name, logo_url, official_address")
    .eq("id", orgId)
    .single();

  // 2. Header: Logo & Org Name
  let currentY = 15;
  
  if (org?.logo_url) {
    try {
      const img = new Image();
      img.src = org.logo_url;
      await new Promise((resolve, reject) => {
        img.onload = resolve;
        img.onerror = reject;
      });
      
      const imgWidth = 40;
      const imgHeight = (img.naturalHeight / img.naturalWidth) * imgWidth;
      doc.addImage(img, 'PNG', 15, currentY, imgWidth, imgHeight);
      currentY += imgHeight + 10;
    } catch (e) {
      console.error("Failed to load logo", e);
      currentY += 10;
    }
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text(org?.official_name || "Clinical Report", 15, currentY);
  currentY += 8;
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(100);
  doc.text(org?.official_address || "", 15, currentY);
  currentY += 15;

  // 3. Document Title
  doc.setDrawColor(200);
  doc.line(15, currentY, pageWidth - 15, currentY);
  currentY += 10;

  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0);
  doc.text(questionnaireName.toUpperCase(), 15, currentY);
  currentY += 10;

  // 4. Meta Information
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text("CLIENT DETAILS", 15, currentY);
  doc.text("ASSESSMENT DETAILS", 110, currentY);
  currentY += 6;

  doc.setFont("helvetica", "normal");
  doc.setTextColor(80);
  doc.text(`Name: ${clientName}`, 15, currentY);
  doc.text(`Specialist: ${specialistName}`, 110, currentY);
  currentY += 5;
  doc.text(`UHID: ${uhid}`, 15, currentY);
  doc.text(`Date: ${new Date(respondedAt).toLocaleDateString()}`, 110, currentY);
  currentY += 15;

  // 5. Answers Table
  const tableData = answers.map((q, idx) => [
    idx + 1,
    q.question,
    Array.isArray(q.answer) ? q.answer.join(", ") : q.answer || "N/A",
    q.score !== undefined ? q.score : "-"
  ]);

  autoTable(doc, {
    startY: currentY,
    head: [['#', 'QUESTION', 'RESPONSE', 'SCORE']],
    body: tableData,
    theme: 'grid',
    headStyles: { 
      fillColor: [15, 23, 42], 
      textColor: [255, 255, 255],
      fontSize: 9,
      fontStyle: 'bold'
    },
    styles: { 
      fontSize: 8,
      cellPadding: 4
    },
    columnStyles: {
      0: { cellWidth: 10 },
      1: { cellWidth: 80 },
      2: { cellWidth: 70 },
      3: { cellWidth: 20, halign: 'center' }
    }
  });

  currentY = (doc as any).lastAutoTable.finalY + 15;

  // 6. Clinical Interpretation
  if (interpretation) {
    if (currentY > 240) {
      doc.addPage();
      currentY = 20;
    }

    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(0);
    doc.text("CLINICAL INTERPRETATION & RECOMMENDATIONS", 15, currentY);
    currentY += 8;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(60);
    
    const splitText = doc.splitTextToSize(interpretation, pageWidth - 30);
    doc.text(splitText, 15, currentY);
    currentY += (splitText.length * 6) + 15;
  }

  // 7. Footer
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      `Generated by ISHPO Health Hub on ${new Date().toLocaleString()} | Page ${i} of ${pageCount}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: "center" }
    );
  }

  doc.save(`${clientName.replace(/\s+/g, '_')}_${questionnaireName.replace(/\s+/g, '_')}_Report.pdf`);
};
