import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { supabase } from "@/integrations/supabase/client";

interface ExportData {
  clientName: string;
  uhid: string;
  questionnaireName: string;
  specialistName: string;
  respondedAt: string;
  answers: any[];
  interpretation: string;
  orgId: string;
}

export const exportQuestionnairePDF = async (data: ExportData) => {
  const { 
    clientName, 
    uhid, 
    questionnaireName, 
    specialistName, 
    respondedAt, 
    answers, 
    interpretation, 
    orgId 
  } = data;

  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // 1. Fetch Org Branding
  const { data: org } = await supabase
    .from("organizations")
    .select("official_name, logo_url, official_address")
    .eq("id", orgId)
    .single();

  // 2. Header: Logo & Org Name
  let currentY = 15;
  
  if (org?.logo_url) {
    try {
      const img = new Image();
      img.src = org.logo_url;
      await new Promise((resolve, reject) => {
        img.onload = resolve;
        img.onerror = reject;
      });
      
      const imgWidth = 40;
      const imgHeight = (img.naturalHeight / img.naturalWidth) * imgWidth;
      doc.addImage(img, 'PNG', 15, currentY, imgWidth, imgHeight);
      currentY += imgHeight + 10;
    } catch (e) {
      console.error("Failed to load logo", e);
      currentY += 10;
    }
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text(org?.official_name || "Clinical Report", 15, currentY);
  currentY += 8;
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(100);
  doc.text(org?.official_address || "", 15, currentY);
  currentY += 15;

  // 3. Document Title
  doc.setDrawColor(200);
  doc.line(15, currentY, pageWidth - 15, currentY);
  currentY += 10;

  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0);
  doc.text(questionnaireName.toUpperCase(), 15, currentY);
  currentY += 10;

  // 4. Meta Information
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text("CLIENT DETAILS", 15, currentY);
  doc.text("ASSESSMENT DETAILS", 110, currentY);
  currentY += 6;

  doc.setFont("helvetica", "normal");
  doc.setTextColor(80);
  doc.text(`Name: ${clientName}`, 15, currentY);
  doc.text(`Specialist: ${specialistName}`, 110, currentY);
  currentY += 5;
  doc.text(`UHID: ${uhid}`, 15, currentY);
  doc.text(`Date: ${new Date(respondedAt).toLocaleDateString()}`, 110, currentY);
  currentY += 15;

  // 5. Answers Table
  const tableData = answers.map((q, idx) => {
    let responseText = q.answer || "N/A";
    
    if (Array.isArray(q.answer)) {
      responseText = q.answer.join(", ");
    } else if (q.type === 'range') {
      const limit = q.scaleLimit || 10;
      const score = parseInt(q.answer) || 0;
      let contextLabel = "";
      
      if (score === 1 && q.minLabel) contextLabel = ` (${q.minLabel})`;
      if (score === limit && q.maxLabel) contextLabel = ` (${q.maxLabel})`;
      
      responseText = `${score}/${limit}${contextLabel}`;
    }

    return [
      idx + 1,
      q.question,
      responseText,
      q.score !== undefined ? q.score : "-"
    ];
  });

  autoTable(doc, {
    startY: currentY,
    head: [['#', 'QUESTION', 'RESPONSE', 'SCORE']],
    body: tableData,
    theme: 'grid',
    headStyles: { 
      fillColor: [15, 23, 42], 
      textColor: [255, 255, 255], 
      fontStyle: 'bold' 
    },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    styles: { fontSize: 9, cellPadding: 5 }
  });

  const finalY = (doc as any).lastAutoTable.finalY;

  // 6. Cumulative Score Summary
  const totalScore = answers.reduce((acc, q) => acc + (q.score || 0), 0);
  const hasScoring = answers.some(q => q.score !== undefined);

  if (hasScoring) {
    doc.setFillColor(15, 23, 42);
    doc.roundedRect(14, finalY + 10, 182, 15, 3, 3, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text(`CUMULATIVE ASSESSMENT SCORE: ${totalScore}`, 20, finalY + 20);
  }

  // 7. Clinical Interpretation
  if (interpretation) {
    const interpretationY = hasScoring ? finalY + 40 : finalY + 15;
    doc.setTextColor(100);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.text("CLINICAL INTERPRETATION & RECOMMENDATIONS", 14, interpretationY);
    
    doc.setTextColor(50);
    doc.setFont("helvetica", "normal");
    const splitText = doc.splitTextToSize(interpretation, 182);
    doc.text(splitText, 14, interpretationY + 10);
  }

  // 8. Footer
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setDrawColor(241, 245, 249);
    doc.line(14, 280, 196, 280);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(`Generated by ISHPO Hub • Page ${i} of ${pageCount}`, 14, 285);
  }

  doc.save(`${clientName.replace(/\s+/g, '_')}_${questionnaireName.replace(/\s+/g, '_')}_Report.pdf`);
};
