import React, { useEffect, useState, useMemo } from "react";
import { ParsedAssessmentData, getStatusFromPercent, StatusGrade } from "./XlsParser";
import { Card, CardContent } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Pencil, RotateCcw, Activity, Calendar } from "lucide-react";

interface EditableReportProps {
  data: ParsedAssessmentData;
  activeTestIndex: number;
  reassessmentDate: string;
  onReassessmentDateChange: (date: string) => void;
  onReportTextsChange: (texts: Record<string, string>) => void;
  reportTexts: Record<string, string>;
  setReportTexts: React.Dispatch<React.SetStateAction<Record<string, string>>>;
  reportTitle: string;
  onReportTitleChange: (title: string) => void;
  readOnly?: boolean;
}

const calculateAge = (birthdateStr: string) => {
  if (!birthdateStr || birthdateStr === "—") return "";
  const birthDate = new Date(birthdateStr);
  const today = new Date();
  let age = today.getFullYear() - birthDate.getFullYear();
  const m = today.getMonth() - birthDate.getMonth();
  if (m < 0 || (m === 0 && today.getDate() < birthDate.getDate())) {
    age--;
  }
  return isNaN(age) ? "" : `${age} years old`;
};

export default function EditableReport({
  data,
  activeTestIndex,
  reassessmentDate,
  onReassessmentDateChange,
  onReportTextsChange,
  reportTexts,
  setReportTexts,
  reportTitle,
  onReportTitleChange,
  readOnly = false,
}: EditableReportProps) {
  const currentTest = data.client.tests.find((t) => t.index === activeTestIndex) || data.client.latestTest;
  const testIndex = activeTestIndex - 1;

  // Track dirty flags
  const [dirtyFields, setDirtyFields] = useState<Record<string, boolean>>({});

  // Generate all auto-populated texts dynamically
  const autoGeneratedTexts = useMemo(() => {
    if (!currentTest) return {};

    // 1. Clinical Summary
    const ageStr = calculateAge(data.client.birthdate);
    const ageText = ageStr ? `, ${ageStr},` : "";
    const baseSummary = `${data.client.name}${ageText} assessed on ${currentTest.date}. ${currentTest.type}. Height: ${currentTest.height || "—"} cm, Weight: ${currentTest.weight || "—"} kg, BMI: ${currentTest.bmi || "—"}.`;
    const count = data.client.tests.length;
    const seriesText = count > 1 ? ` This is the Test ${currentTest.index} assessment in a series of ${count} tests.` : "";
    const clinicalSummary = `${baseSummary}${seriesText}`;

    // 2. Strength Findings
    const strengthSummaries: string[] = [];
    Object.entries(data.strengthSummary).forEach(([key, summary]: [string, any]) => {
      const avg = summary.testAverages[testIndex];
      if (avg === null || avg === undefined) return;

      let gradeLabel = "Moderate Strength";
      if (avg >= 10) gradeLabel = "Good Strength";
      else if (avg >= -10) gradeLabel = "Moderate Strength";
      else if (avg >= -30) gradeLabel = "Needs Improvement";
      else gradeLabel = "Priority Intervention Required";

      let text = `${summary.label} isometric strength averaged ${avg > 0 ? "+" : ""}${avg.toFixed(1)}% relative to reference values, indicating ${gradeLabel}.`;

      if (testIndex > 0) {
        const prevAvg = summary.testAverages[testIndex - 1];
        if (prevAvg !== null && prevAvg !== undefined) {
          const diff = avg - prevAvg;
          const changeWord = diff >= 0 ? "improvement" : "decline";
          const prevTestDate = data.client.tests[testIndex - 1]?.date || `Test ${activeTestIndex - 1}`;
          text += ` Compared to previous assessment on ${prevTestDate}, this represents an ${changeWord} of ${Math.abs(diff).toFixed(1)} percentage points.`;
        }
      }
      strengthSummaries.push(text);
    });
    const strengthFindings = strengthSummaries.length > 0 
      ? strengthSummaries.join("\n\n") 
      : "No rankable strength test metrics recorded for this session.";

    // 3. Mobility Findings
    const mobilityMetrics = data.metrics.mobility;
    const rankableMobility = mobilityMetrics.filter(m => m.isRankable && m.tests[testIndex]?.percentRef !== null);
    let mobilityFindings = "";
    if (rankableMobility.length === 0) {
      mobilityFindings = "No rankable mobility test metrics recorded for this session.";
    } else {
      const sortedMob = [...rankableMobility].sort((a, b) => {
        return (a.tests[testIndex].percentRef || 0) - (b.tests[testIndex].percentRef || 0);
      });
      const lowestMob = sortedMob[0];
      const highestMob = sortedMob[sortedMob.length - 1];
      
      let text = `Mobility assessment: `;
      if (lowestMob && (lowestMob.tests[testIndex].percentRef || 0) < 0) {
        text += `Deficits observed in ${lowestMob.label} (${lowestMob.tests[testIndex].percentRef!}% vs ref). `;
      }
      if (highestMob && (highestMob.tests[testIndex].percentRef || 0) >= 0) {
        text += `Optimal range of motion verified in ${highestMob.label} (${highestMob.tests[testIndex].percentRef!}% vs ref). `;
      }
      const poorCount = rankableMobility.filter(m => (m.tests[testIndex].percentRef || 0) < -10).length;
      text += `Overall, ${poorCount} out of ${rankableMobility.length} measured mobility indicators showed significant limitations (below -10% reference limit).`;
      mobilityFindings = text;
    }

    // 4. Balance Findings
    const balanceMetrics = data.metrics.balance;
    const rankableBal = balanceMetrics.filter(m => m.isRankable && m.tests[testIndex]?.percentRef !== null);
    let balanceFindings = "";
    if (rankableBal.length === 0) {
      balanceFindings = "No rankable strength balance metrics recorded for this session.";
    } else {
      const outOfRange = rankableBal.filter(m => {
        const val = m.tests[testIndex].percentRef!;
        return val < -10 || val >= 10;
      });
      const inRangeCount = rankableBal.length - outOfRange.length;
      const areAllInRange = outOfRange.length === 0;

      let text = `Strength balance ratios ${areAllInRange ? "are" : "are not"} within normal reference ranges across ${rankableBal.length} measured ratios. `;
      text += `${inRangeCount} ratios met target guidelines. `;

      if (outOfRange.length > 0) {
        const sortedBal = [...outOfRange].sort((a, b) => {
          return (a.tests[testIndex].percentRef || 0) - (b.tests[testIndex].percentRef || 0);
        });
        const worstBal = sortedBal[0];
        text += `Deficit flagged in ${worstBal.label} (${worstBal.tests[testIndex].percentRef!}% deviation).`;
      }
      balanceFindings = text;
    }

    return {
      clinicalSummary,
      strengthFindings,
      mobilityFindings,
      balanceFindings,
      clinicalImpression: "",
      recommendations: "",
    };
  }, [data, activeTestIndex, currentTest, testIndex]);

  // Load auto-generated values into state on mount or active test change
  useEffect(() => {
    if (readOnly) return;
    const initialTexts: Record<string, string> = {};
    Object.keys(autoGeneratedTexts).forEach((key) => {
      initialTexts[key] = reportTexts[key] !== undefined && dirtyFields[key]
        ? reportTexts[key]
        : (autoGeneratedTexts as any)[key];
    });
    setReportTexts(initialTexts);
    onReportTextsChange(initialTexts);
  }, [autoGeneratedTexts, activeTestIndex, readOnly]);

  const handleTextChange = (field: string, val: string) => {
    const isDirty = val !== (autoGeneratedTexts as any)[field];
    setDirtyFields((prev) => ({ ...prev, [field]: isDirty }));
    
    const updated = { ...reportTexts, [field]: val };
    setReportTexts(updated);
    onReportTextsChange(updated);
  };

  const handleResetField = (field: string) => {
    setDirtyFields((prev) => ({ ...prev, [field]: false }));
    const defaultText = (autoGeneratedTexts as any)[field];
    const updated = { ...reportTexts, [field]: defaultText };
    setReportTexts(updated);
    onReportTextsChange(updated);
  };

  const renderTextAreaSection = (
    field: string,
    title: string,
    placeholder: string,
    isAutoGenerated = true
  ) => {
    const isDirty = dirtyFields[field];
    const val = reportTexts[field] || "";

    return (
      <div className="space-y-2 relative">
        <div className="flex justify-between items-center">
          <Label className="text-xs font-black uppercase tracking-wider text-slate-500 flex items-center gap-1.5">
            {title}
            {isDirty && !readOnly && (
              <span className="text-[8px] font-black uppercase bg-primary/10 text-primary border border-primary/20 px-1.5 py-0.5 rounded-md tracking-wider">
                Edited
              </span>
            )}
          </Label>
          <div className="flex gap-2">
            {isAutoGenerated && !readOnly && (
              <span className="text-[9px] font-bold text-muted-foreground uppercase tracking-widest flex items-center gap-1">
                <Pencil className="w-2.5 h-2.5" /> Auto-generated
              </span>
            )}
            {isDirty && !readOnly && (
              <button
                type="button"
                onClick={() => handleResetField(field)}
                className="text-[9px] font-black text-red-500 uppercase tracking-widest hover:underline flex items-center gap-1"
              >
                <RotateCcw className="w-2.5 h-2.5" /> Reset
              </button>
            )}
          </div>
        </div>
        <Textarea
          value={val}
          onChange={(e) => handleTextChange(field, e.target.value)}
          placeholder={placeholder}
          readOnly={readOnly}
          className="min-h-[100px] rounded-2xl border-border bg-white dark:bg-slate-900 shadow-sm text-sm"
        />
      </div>
    );
  };

  const getStatusBadge = (percent: number | null): React.ReactNode => {
    if (percent === null) return <span className="text-slate-400">—</span>;
    const status = getStatusFromPercent(percent);
    const statusColors: Record<StatusGrade, string> = {
      good: "bg-green-50 text-green-600 border-green-200 dark:bg-green-950/20",
      moderate: "bg-amber-50 text-amber-600 border-amber-200 dark:bg-amber-950/20",
      "needs-work": "bg-orange-50 text-orange-600 border-orange-200 dark:bg-orange-950/20",
      priority: "bg-red-50 text-red-600 border-red-200 dark:bg-red-950/20",
    };
    const sign = percent > 0 ? "+" : "";
    return (
      <span className={`px-2 py-0.5 rounded-full border text-[9px] font-black tracking-wider uppercase ${statusColors[status]}`}>
        {sign}{percent.toFixed(1)}%
      </span>
    );
  };

  return (
    <div className="space-y-6">
      {/* 6 Report Fields Card */}
      <Card className="gradient-card border-border shadow-sm">
        <CardContent className="pt-6 space-y-6">
          <div className="flex items-center gap-2 border-b pb-3">
            <div className="w-1 h-4 bg-primary rounded-full" />
            <h3 className="font-bold text-base uppercase tracking-wider text-foreground">
              Clinical Summaries & Observations
            </h3>
          </div>

          <div className="space-y-6">
            {/* Report Title / Assessment Name */}
            <div className="space-y-2 p-4 border border-dashed rounded-2xl bg-white/40 dark:bg-slate-900/10">
              <Label className="text-xs font-black uppercase tracking-wider text-slate-500">
                Assessment Name / Report Title
              </Label>
              <Input
                type="text"
                value={reportTitle}
                onChange={(e) => onReportTitleChange(e.target.value)}
                placeholder="Enter report title (e.g., Muscle Heatmap Assessment)..."
                readOnly={readOnly}
                className="bg-white dark:bg-slate-900 border-border rounded-xl text-xs font-bold focus:ring-1 focus:ring-primary focus:border-primary"
              />
            </div>

            {renderTextAreaSection("clinicalSummary", "Clinical Summary", "Auto-generating summary...")}
            {renderTextAreaSection("strengthFindings", "Strength Findings", "Auto-generating findings...")}
            {renderTextAreaSection("mobilityFindings", "Mobility Findings", "Auto-generating findings...")}
            {renderTextAreaSection("balanceFindings", "Strength Balance Findings", "Auto-generating findings...")}
            {renderTextAreaSection("clinicalImpression", "Clinical Impression / Diagnosis", "Clinician notes — clinical interpretation and diagnosis...", false)}
            {renderTextAreaSection("recommendations", "Recommendations", "Recommended interventions, exercises, follow-up timeline...", false)}

            {/* Reassessment Date */}
            <div className="space-y-2 p-4 border border-dashed rounded-2xl bg-white/40 dark:bg-slate-900/10">
              <Label className="text-xs font-black uppercase tracking-wider text-slate-500 flex items-center gap-1.5">
                <Calendar className="w-4 h-4 text-primary" /> Reassessment Due Date
              </Label>
              <Input
                type="date"
                value={reassessmentDate}
                onChange={(e) => onReassessmentDateChange(e.target.value)}
                readOnly={readOnly}
                className="bg-white dark:bg-slate-900 border-border rounded-xl text-xs"
              />
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Detailed Sheet Data collapsing panel */}
      <Card className="gradient-card border-border shadow-sm">
        <CardContent className="pt-6">
          <Accordion type="single" collapsible className="w-full">
            {/* Mobility Tables */}
            <AccordionItem value="mobility" className="border-b-0">
              <AccordionTrigger className="hover:no-underline py-3">
                <div className="flex items-center gap-2">
                  <Activity className="w-4 h-4 text-primary" />
                  <span className="font-bold text-sm text-foreground uppercase tracking-wider">
                    Full Mobility Metrics Table ({data.metrics.mobility.length} metrics)
                  </span>
                </div>
              </AccordionTrigger>
              <AccordionContent className="pt-3">
                <div className="overflow-x-auto rounded-xl border border-border bg-white dark:bg-slate-900">
                  <Table>
                    <TableHeader className="bg-muted/40">
                      <TableRow>
                        <TableHead className="text-[9px] font-black uppercase">Category</TableHead>
                        <TableHead className="text-[9px] font-black uppercase">Measurement</TableHead>
                        <TableHead className="text-[9px] font-black uppercase text-center">Reference</TableHead>
                        {data.client.tests.map((t) => (
                          <React.Fragment key={t.index}>
                            <TableHead className="text-[9px] font-black uppercase text-center">T{t.index} Result</TableHead>
                            <TableHead className="text-[9px] font-black uppercase text-center">T{t.index} % Ref.</TableHead>
                          </React.Fragment>
                        ))}
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {data.metrics.mobility.map((m) => (
                        <TableRow key={m.key} className="hover:bg-primary/[0.01]">
                          <TableCell className="text-xs font-semibold text-slate-500 uppercase tracking-tighter truncate max-w-[120px]">
                            {m.category}
                          </TableCell>
                          <TableCell className="text-xs font-bold text-foreground">
                            {m.label}
                          </TableCell>
                          <TableCell className="text-xs text-center font-mono text-muted-foreground">
                            {m.referenceValue ?? "—"}
                          </TableCell>
                          {m.tests.map((t, idx) => (
                            <React.Fragment key={idx}>
                              <TableCell className="text-xs text-center font-mono">{t.result ?? "—"}</TableCell>
                              <TableCell className="text-xs text-center font-mono">{getStatusBadge(t.percentRef)}</TableCell>
                            </React.Fragment>
                          ))}
                        </TableRow>
                      ))}
                    </TableBody>
                  </Table>
                </div>
              </AccordionContent>
            </AccordionItem>

            {/* Strength Tables */}
            <AccordionItem value="strength" className="border-b-0">
              <AccordionTrigger className="hover:no-underline py-3">
                <div className="flex items-center gap-2">
                  <Activity className="w-4 h-4 text-primary" />
                  <span className="font-bold text-sm text-foreground uppercase tracking-wider">
                    Full Strength Metrics Table ({data.metrics.strength.length} metrics)
                  </span>
                </div>
              </AccordionTrigger>
              <AccordionContent className="pt-3">
                <div className="overflow-x-auto rounded-xl border border-border bg-white dark:bg-slate-900">
                  <Table>
                    <TableHeader className="bg-muted/40">
                      <TableRow>
                        <TableHead className="text-[9px] font-black uppercase">Category</TableHead>
                        <TableHead className="text-[9px] font-black uppercase">Measurement</TableHead>
                        <TableHead className="text-[9px] font-black uppercase text-center">Reference</TableHead>
                        {data.client.tests.map((t) => (
                          <React.Fragment key={t.index}>
                            <TableHead className="text-[9px] font-black uppercase text-center">T{t.index} Result</TableHead>
                            <TableHead className="text-[9px] font-black uppercase text-center">T{t.index} % Ref.</TableHead>
                          </React.Fragment>
                        ))}
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {data.metrics.strength.map((m) => (
                        <TableRow key={m.key} className="hover:bg-primary/[0.01]">
                          <TableCell className="text-xs font-semibold text-slate-500 uppercase tracking-tighter truncate max-w-[120px]">
                            {m.category}
                          </TableCell>
                          <TableCell className="text-xs font-bold text-foreground">
                            {m.label}
                          </TableCell>
                          <TableCell className="text-xs text-center font-mono text-muted-foreground">
                            {m.referenceValue ?? "—"}
                          </TableCell>
                          {m.tests.map((t, idx) => (
                            <React.Fragment key={idx}>
                              <TableCell className="text-xs text-center font-mono">{t.result ?? "—"}</TableCell>
                              <TableCell className="text-xs text-center font-mono">{getStatusBadge(t.percentRef)}</TableCell>
                            </React.Fragment>
                          ))}
                        </TableRow>
                      ))}
                    </TableBody>
                  </Table>
                </div>
              </AccordionContent>
            </AccordionItem>

            {/* Strength Balance Tables */}
            <AccordionItem value="balance" className="border-b-0">
              <AccordionTrigger className="hover:no-underline py-3">
                <div className="flex items-center gap-2">
                  <Activity className="w-4 h-4 text-primary" />
                  <span className="font-bold text-sm text-foreground uppercase tracking-wider">
                    Full Strength Balance Table ({data.metrics.balance.length} metrics)
                  </span>
                </div>
              </AccordionTrigger>
              <AccordionContent className="pt-3">
                <div className="overflow-x-auto rounded-xl border border-border bg-white dark:bg-slate-900">
                  <Table>
                    <TableHeader className="bg-muted/40">
                      <TableRow>
                        <TableHead className="text-[9px] font-black uppercase">Category</TableHead>
                        <TableHead className="text-[9px] font-black uppercase">Measurement</TableHead>
                        <TableHead className="text-[9px] font-black uppercase text-center">Reference</TableHead>
                        {data.client.tests.map((t) => (
                          <React.Fragment key={t.index}>
                            <TableHead className="text-[9px] font-black uppercase text-center">T{t.index} Result</TableHead>
                            <TableHead className="text-[9px] font-black uppercase text-center">T{t.index} % Ref.</TableHead>
                          </React.Fragment>
                        ))}
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {data.metrics.balance.map((m) => (
                        <TableRow key={m.key} className="hover:bg-primary/[0.01]">
                          <TableCell className="text-xs font-semibold text-slate-500 uppercase tracking-tighter truncate max-w-[120px]">
                            {m.category}
                          </TableCell>
                          <TableCell className="text-xs font-bold text-foreground">
                            {m.label}
                          </TableCell>
                          <TableCell className="text-xs text-center font-mono text-muted-foreground">
                            {m.referenceValue ?? "—"}
                          </TableCell>
                          {m.tests.map((t, idx) => (
                            <React.Fragment key={idx}>
                              <TableCell className="text-xs text-center font-mono">{t.result ?? "—"}</TableCell>
                              <TableCell className="text-xs text-center font-mono">{getStatusBadge(t.percentRef)}</TableCell>
                            </React.Fragment>
                          ))}
                        </TableRow>
                      ))}
                    </TableBody>
                  </Table>
                </div>
              </AccordionContent>
            </AccordionItem>
          </Accordion>
        </CardContent>
      </Card>
    </div>
  );
}
